import { Section } from "../modal/Section";

export const website1: Section[] = [
  {
      id: "69e7ed7e-889d-41c0-a1d9-62bd150401e2",
      name: "Header",
      version: "v1", // Add version property
      style: "CLASSIC", // Add style property
      path: "index",
      data: {
        type: "Header",
        id: "001",
        title: "Hero Banner!",
        subTitle: "Hero Banner Sub Title is here",
        description: "Hero Banner Paragraph is here",
        version: "v1",
        style: "CLASSIC",
        services: null,
        products: null,
        portfolios: null,
        images: null,
        blogs : null,
        testimonials: null,
        faqs: null,
        contactUs:null,
      },
    },
{
  id: "69e7ed7e-889d-41c0-a1d9-62bd150401e2",
  name: "Herobanner",
  version: "v1", // Add version property
  style: "MODERN", // Add style property
  path: "index",
  data: {
    type: "HeroBanner",
    id: "002",
    title: "Software Engineer !",
    subTitle: "Loonds Spa App Alpha Vercel",
    description: "Hero Banner Paragraph is here",
    version: "v1",
    style: "MODERN",
    services: null,
    portfolios: null,
    products: null,
    images: [
      {
          id: '1',
          imageSrc: 'https://tailwindui.com/img/ecommerce-images/home-page-02-edition-01.jpg',
          imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
      },
    ],
    blogs : null,
    testimonials: null,
    faqs: null,
    contactUs:null,
  },
},
{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: "Service",
  version: "v1",
  style: "MODERN",
  path: "index",
  data: {
    type: "AboutUs",
    id: "003",
    title: "About us is here!",
    subTitle: "Hero Banner Sub Title is here",
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    version: "v1",
    style: "MODERN",
    services: null,
    products: null,
    images: null,
    blogs : null,
    testimonials: null,
    portfolios: null,
    faqs: null,
    contactUs:null,
  },
},
{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: "Gallery",
  version: "v1",
  style: "CLASSIC",
  path: "index",
  data: {
    type: "Gallery",
    id: "004",
    title: "Gallery !",
    subTitle: "Hero Banner Sub Title is here",
    description: "Hero Banner Paragraph is here",
    version: "v1",
    style: "CLASSIC",
    services: null,
    products: null,
    portfolios: null,
    faqs: null,
    images: [
      {
          id: '1',
          imageSrc: 'https://tailwindui.com/img/ecommerce-images/home-page-02-edition-01.jpg',
          imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
      },
      {
          id: '2',
          imageSrc: 'https://images.unsplash.com/photo-1684752097893-13785863f9a1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=435&q=80',
          imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
      },
      {
          id: '3',
          imageSrc: 'https://images.unsplash.com/photo-1682695797221-8164ff1fafc9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80',
          imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
      },
      {
          id: '4',
          imageSrc: 'https://images.unsplash.com/photo-1682695797221-8164ff1fafc9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80',
          imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
      },
  ],
  blogs : null,
  testimonials: null,
  contactUs:null,
  },
},
{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: "Service",
  version: "v1",
  style: "CLASSIC",
  path: "index",
  data: {
    type: "Service",
    id: "k",
    title: "Our Services",
    subTitle: "Hero Banner Sub Title is here",
    description: "Hero Banner Paragraph is here",
    version: "v1",
    style: "CLASSIC",
    blogs : null,
    faqs: null,
    contactUs:null,
    portfolios: null,
    services: [
      {
          id: 1,
          title: 'Hosting Space',
          body: 'We dejoy working with discerning clients, people for whom qualuty, service, integrity & aesthetics.',
          imageSrc: 'https://htmldemo.zcubethemes.com/riorelax/img/icon/sve-icon3.png',
          imageAlt: 'parking icon',
      },
      {
          id: 2,
          title: '27/7 Service',
          body: 'We dejoy working with discerning clients, people for whom qualuty, service, integrity & aesthetics.',
          imageSrc: 'https://htmldemo.zcubethemes.com/riorelax/img/icon/fe-icon01.png',
          imageAlt: 'parking icon',
      },
      {
          id: 3,
          title: 'Fibre Internet',
          body: 'We dejoy working with discerning clients, people for whom qualuty, service, integrity & aesthetics.',
          imageSrc: 'https://htmldemo.zcubethemes.com/riorelax/img/icon/sve-icon2.png',
          imageAlt: 'parking icon',
      },
      
    ],
    products: null,
    images: null,
    testimonials: null,
  },
},
{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: "Service",
  version: "v1",
  style: "CLASSIC",
  path: "index",
  data: {
    type: "Blog",
    id: "k",
    title: "Hero Banner!",
    subTitle: "Hero Banner Sub Title is here",
    description: "Hero Banner Paragraph is here",
    version: "v1",
    style: "CLASSIC",
    services: null,
    products: null,
    faqs: null,
    contactUs:null,
    portfolios: null,
    blogs : [
      {
        id: "1",
        title: "Blog Post 1",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        descriptionContext: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nonummy tincidunt ut lacreet dolore magna aliguam erat volutpat.",
        imageSrc: "https://images.unsplash.com/photo-1605181063694-e64a8e7a267f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=435&q=80",
        imageAlt: 'Tall slender porcelain bottle with natural clay textured body and cork stopper.',
      },
      {
        id: "2",
        title: "Blog Post 2",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        descriptionContext: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nonummy tincidunt ut lacreet dolore magna aliguam erat volutpat.",
        imageSrc: "https://plus.unsplash.com/premium_photo-1674086970773-726e445f5802?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1172&q=80",
        imageAlt: 'Tall slender porcelain bottle with natural clay textured body and cork stopper.',
      },
      {
        id: "3",
        title: "Blog Post 3",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        descriptionContext: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nonummy tincidunt ut lacreet dolore magna aliguam erat volutpat.",
        imageSrc: "https://plus.unsplash.com/premium_photo-1674086970773-726e445f5802?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1172&q=80",
        imageAlt: 'Tall slender porcelain bottle with natural clay textured body and cork stopper.',
      },
      {
        id: "4",
        title: "Blog Post 3",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        descriptionContext: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nonummy tincidunt ut lacreet dolore magna aliguam erat volutpat.",
        imageSrc: "https://plus.unsplash.com/premium_photo-1674086970773-726e445f5802?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1172&q=80",
        imageAlt: 'Tall slender porcelain bottle with natural clay textured body and cork stopper.',
      },
    ],
    images: null,
    testimonials: null,
  },
},
{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: "Service",
  version: "v1",
  style: "CLASSIC",
  path: "index",
  data: {
    type: "Testimonial",
    id: "k",
    title: "Hero Banner!",
    subTitle: "Hero Banner Sub Title is here",
    description: "Hero Banner Paragraph is here",
    version: "v1",
    style: "CLASSIC",
    services: null,
    products: null,
    images: null,
    blogs : null,
    faqs: null,
    portfolios: null,
    contactUs:null,
    testimonials: [
      {
        id: "1",
        name: "John Doe",
        designation: "Graphic Designer",
        imageSrc: "https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(2).jpg",
        imageAlt: "Graphic Designer",
        testimonial:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac magna sit amet risus tristique interdum, at vel velit in hac habitasse platea dictumst.",
    },
    {
        id: "2",
        name: "John Doe",
        designation: "John Doe",
        imageSrc: "https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(1).jpg",
        imageAlt: "John Doe",
        testimonial:
            "Praesent placerat enim ut ex tincidunt vehicula. Fusce sit amet dui tellus. Morbi sagittis, quam nec venenatis lobortis, mi risus tempus nulla, sed porttitor est nibh at nulla.",
    },
    {
        id: "3",
        name: "John Doe",
        designation: "John Doe",
        imageSrc: "https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(9).jpg",
        imageAlt: "John Doe",
        testimonial:
            "Ut posuere, ex a fringilla hendrerit, nulla metus gravida mi, in hendrerit quam odio sed est. Vestibulum nec finibus nisi. Aliquam et ipsum nulla.",
    },
    ],
  },
},
{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: "ContactUs",
  version: "v2",
  style: "CLASSIC",
  path: "index",
  data: {
    type: "ContactUs",
    id: "k",
    title: "Get in Touch",
    subTitle: "Hero Banner Sub Title is here",
    description: "Hero Banner Paragraph is here",
    version: "v2",
    style: "CLASSIC",
    services: null,
    products: null,
    images: null,
    testimonials: null,
    portfolios: null,
    faqs: null,
    blogs : null,
    contactUs: {
      address : "Village Kimughat P.O. Garkhal, Tehsil, Kasauli, Himachal Pradesh 173201",
      email: "gayatrilodgekasauli@gmail.com",
      phone: "+91-9857315551",
    },
  },
},
{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: "Faq",
  version: "v1",
  style: "CLASSIC",
  path: "index",
  data: {
    type: "FAQ",
    id: "k",
    title: "Hero Banner!",
    subTitle: "Hero Banner Sub Title is here",
    description: "Hero Banner Paragraph is here",
    version: "v1",
    style: "CLASSIC",
    services: null,
    products: null,
    images: null,
    blogs : null,
    testimonials: null,
    contactUs:null,
    portfolios: null,
    faqs: [
      {
        id:1,
        question: 'Q.What is bla bla ?',
        answer: 'Ans:The standard check-in time at Gayatri Lodge is 2:00 PM, and the check-out time is 12:00 PM (noon). However, early check-in or late check-out requests can be accommodated based on availability and may be subject to additional charges.',
      },
      {
        id:2,
        question: 'Q.What Service are provided at Loonds spa?',
        answer: 'Ans:Gayatri Lodge offers a range of amenities to make your stay comfortable. Some of the amenities include clean and well-furnished rooms, air conditioning, television, attached bathroom with hot water facility, room service, Wi-Fi access, and complimentary toiletries.',
      },
      {
        id:3,
        question: 'Q.Is there Domain parking provide loonds?',
        answer: 'Ans:Yes, Gayatri Lodge provides parking facilities for guests. You can safely park your vehicle during your stay at the lodge. However, parking availability may be limited, so its advisable to inform the lodge in advance if you require parking.',
      },
  ],
  },
},
{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: "Footer",
  version: "v1",
  style: "CLASSIC",
  path: "index",
  data: {
    type: "Footer",
    id: "k",
    title: "Hero Banner!",
    subTitle: "Hero Banner Sub Title is here",
    description: "Hero Banner Paragraph is here",
    version: "v1",
    style: "CLASSIC",
    services: null,
    portfolios: null,
    products: null,
    blogs : null,
    images: null,
    faqs: null,
    contactUs:null,
    testimonials: null,
  },
},
];
export const website2: Section[] = [
  {
      id: "69e7ed7e-889d-41c0-a1d9-62bd150401e2",
      name: "Header",
      version: "v1", // Add version property
      style: "CLASSIC", // Add style property
      path: "index",
      data: {
        type: "Header",
        id: "001",
        title: "Hero Banner!",
        subTitle: "Hero Banner Sub Title is here",
        description: "Hero Banner Paragraph is here",
        version: "v1",
        style: "CLASSIC",
        services: null,
        products: null,
        portfolios: null,
        images: null,
        blogs : null,
        testimonials: null,
        faqs: null,
        contactUs:null,
      },
    },
{
  id: "69e7ed7e-889d-41c0-a1d9-62bd150401e2",
  name: "Herobanner",
  version: "v1", // Add version property
  style: "CLASSIC", // Add style property
  path: "index",
  data: {
    type: "HeroBanner",
    id: "002",
    title: "Sample Hero Banner is Here !",
    subTitle: "Hero Banner Sub Title is here",
    description: "Hero Banner Paragraph is here",
    version: "v1",
    style: "CLASSIC",
    services: null,
    products: null,
    images: null,
    blogs : null,
    testimonials: null,
    portfolios: null,
    faqs: null,
    contactUs:null,
  },
},
{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: "Service",
  version: "v1",
  style: "MODERN",
  path: "index",
  data: {
    type: "AboutUs",
    id: "003",
    title: "About us!",
    subTitle: "Hero Banner Sub Title is here",
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    version: "v1",
    style: "MODERN",
    services: null,
    products: null,
    images: null,
    blogs : null,
    testimonials: null,
    portfolios: null,
    faqs: null,
    contactUs:null,
  },
},
{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: "Gallery",
  version: "v1",
  style: "MODERN",
  path: "index",
  data: {
    type: "Gallery",
    id: "004",
    title: "Sample Gallery is here!",
    subTitle: "Hero Banner Sub Title is here",
    description: "Hero Banner Paragraph is here",
    version: "v1",
    style: "MODERN",
    services: null,
    products: null,
    portfolios: null,
    faqs: null,
    images: [
      {
          id: '1',
          imageSrc: 'https://tailwindui.com/img/ecommerce-images/home-page-02-edition-01.jpg',
          imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
      },
      {
          id: '2',
          imageSrc: 'https://images.unsplash.com/photo-1684752097893-13785863f9a1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=435&q=80',
          imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
      },
      {
          id: '3',
          imageSrc: 'https://images.unsplash.com/photo-1682695797221-8164ff1fafc9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80',
          imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
      },
      {
          id: '4',
          imageSrc: 'https://images.unsplash.com/photo-1682695797221-8164ff1fafc9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80',
          imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
      },
  ],
  blogs : null,
  testimonials: null,
  contactUs:null,
  },
},
{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: " ",
  version: "v1",
  style: "CLASSIC",
  path: "index",
  data: {
    type: "Product",
    id: "k",
    title: "Our Rooms!",
    subTitle: "Hero Banner Sub Title is here",
    description: "Hero Banner Paragraph is here",
    version: "v1",
    style: "CLASSIC",
    services: null,
    blogs : null,
    portfolios: null,
    products: [
      {
          id: 1,
          name: 'Deluxe Room',
          href: '#',
          description: 'Spacious, elegant, and luxurious accommodation for ultimate comfort.',
          imageSrc: "https://images.unsplash.com/photo-1591088398332-8a7791972843?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1074&q=80",
          imageAlt: 'Tall slender porcelain bottle with natural clay textured body and cork stopper.',
      },
      {
          id: 2,
          name: 'Master Room',
          href: '#',
          description: 'Opulent, indulgent, and exclusive retreat for discerning guests.',
          imageSrc: "https://images.unsplash.com/photo-1568495248636-6432b97bd949?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1074&q=80",
          imageAlt: 'Olive drab green insulated bottle with flared screw lid and flat top.',
      },
      {
          id: 3,
          name: 'Super Room',
          href: '#',
          description: ' Upgraded, luxurious, and lavish accommodation for a remarkable stay.',
          imageSrc: "https://images.unsplash.com/photo-1568495248636-6432b97bd949?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1074&q=80",
          imageAlt: 'Person using a pen to cross a task off a productivity paper card.',
      },
      {
          id: 4,
          name: 'Normal Room',
          href: '#',
          description: 'Comfortable, affordable, and practical choice for a pleasant stay.',
          imageSrc: "https://images.unsplash.com/photo-1568495248636-6432b97bd949?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1074&q=80",
          imageAlt: 'Hand holding black machined steel mechanical pencil with brass tip and top.',
      },
      // More products...
  ],
    images: null,
    faqs: null,
    testimonials: null,
    contactUs:null,
  },
},
{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: "Service",
  version: "v1",
  style: "CLASSIC",
  path: "index",
  data: {
    type: "Service",
    id: "k",
    title: "Our Services",
    subTitle: "Hero Banner Sub Title is here",
    description: "Hero Banner Paragraph is here",
    version: "v1",
    style: "CLASSIC",
    blogs : null,
    faqs: null,
    contactUs:null,
    portfolios: [
      {
        id:1,
          name: 'Desk and Office',
          description: 'Work from home accessories',
          imageSrc: 'https://tailwindui.com/img/ecommerce-images/home-page-02-edition-01.jpg',
          imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
          href: '#',
      },
      {
        id:2,
          name: 'Self-Improvement',
          description: 'Journals and note-taking',
          imageSrc: 'https://tailwindui.com/img/ecommerce-images/home-page-02-edition-02.jpg',
          imageAlt: 'Wood table with porcelain mug, leather journal, brass pen, leather key ring, and a houseplant.',
          href: '#',
      },
      {
        id:3,
          name: 'Self-Improvement',
          description: 'Journals and note-taking',
          imageSrc: 'https://tailwindui.com/img/ecommerce-images/home-page-02-edition-02.jpg',
          imageAlt: 'Wood table with porcelain mug, leather journal, brass pen, leather key ring, and a houseplant.',
          href: '#',
      },
      {
        id:4,
          name: 'Self-Improvement',
          description: 'Journals and note-taking',
          imageSrc: 'https://tailwindui.com/img/ecommerce-images/home-page-02-edition-02.jpg',
          imageAlt: 'Wood table with porcelain mug, leather journal, brass pen, leather key ring, and a houseplant.',
          href: '#',
      },
      {
        id:5,
          name: 'Travel',
          description: 'Daily commute essentials',
          imageSrc: 'https://tailwindui.com/img/ecommerce-images/home-page-02-edition-03.jpg',
          imageAlt: 'Collection of four insulated travel bottles on wooden shelf.',
          href: '#',
      },
  ],
    services: [
      {
          id: 1,
          title: 'Parking Space',
          body: 'We dejoy working with discerning clients, people for whom qualuty, service, integrity & aesthetics.',
          imageSrc: 'https://htmldemo.zcubethemes.com/riorelax/img/icon/sve-icon3.png',
          imageAlt: 'parking icon',
      },
      {
          id: 2,
          title: 'Room Service',
          body: 'We dejoy working with discerning clients, people for whom qualuty, service, integrity & aesthetics.',
          imageSrc: 'https://htmldemo.zcubethemes.com/riorelax/img/icon/fe-icon01.png',
          imageAlt: 'parking icon',
      },
      {
          id: 3,
          title: 'Fibre Internet',
          body: 'We dejoy working with discerning clients, people for whom qualuty, service, integrity & aesthetics.',
          imageSrc: 'https://htmldemo.zcubethemes.com/riorelax/img/icon/sve-icon2.png',
          imageAlt: 'parking icon',
      },
      {
          id: 4,
          title: 'Special Offers',
          body: 'We dejoy working with discerning clients, people for whom qualuty, service, integrity & aesthetics.',
          imageSrc: 'https://htmldemo.zcubethemes.com/riorelax/img/icon/fe-icon08.png',
          imageAlt: 'parking icon',
      },
      {
          id: 5,
          title: 'Best Accommodation',
          body: 'We dejoy working with discerning clients, people for whom qualuty, service, integrity & aesthetics.',
          imageSrc: 'https://htmldemo.zcubethemes.com/riorelax/img/icon/fe-icon05.png',
          imageAlt: 'parking icon',
      },
      {
          id: 6,
          title: 'Breakfast',
          body: 'We dejoy working with discerning clients, people for whom qualuty, service, integrity & aesthetics.',
          imageSrc: 'https://htmldemo.zcubethemes.com/riorelax/img/icon/fe-icon05.png',
          imageAlt: 'parking icon',
      },
    ],
    products: null,
    images: null,
    testimonials: null,
  },
},
{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: "Service",
  version: "v1",
  style: "CLASSIC",
  path: "index",
  data: {
    type: "Blog",
    id: "k",
    title: "Hero Banner!",
    subTitle: "Hero Banner Sub Title is here",
    description: "Hero Banner Paragraph is here",
    version: "v1",
    style: "CLASSIC",
    services: null,
    products: null,
    faqs: null,
    contactUs:null,
    portfolios: null,
    blogs : [
      {
        id: "1",
        title: "Blog Post 1",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        descriptionContext: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nonummy tincidunt ut lacreet dolore magna aliguam erat volutpat.",
        imageSrc: "https://plus.unsplash.com/premium_photo-1674086970773-726e445f5802?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1172&q=80",
        imageAlt: 'Tall slender porcelain bottle with natural clay textured body and cork stopper.',
      },
      {
        id: "2",
        title: "Blog Post 2",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        descriptionContext: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nonummy tincidunt ut lacreet dolore magna aliguam erat volutpat.",
        imageSrc: "https://plus.unsplash.com/premium_photo-1674086970773-726e445f5802?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1172&q=80",
        imageAlt: 'Tall slender porcelain bottle with natural clay textured body and cork stopper.',
      },
      {
        id: "3",
        title: "Blog Post 3",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        descriptionContext: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nonummy tincidunt ut lacreet dolore magna aliguam erat volutpat.",
        imageSrc: "https://plus.unsplash.com/premium_photo-1674086970773-726e445f5802?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1172&q=80",
        imageAlt: 'Tall slender porcelain bottle with natural clay textured body and cork stopper.',
      },
      {
        id: "4",
        title: "Blog Post 3",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        descriptionContext: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nonummy tincidunt ut lacreet dolore magna aliguam erat volutpat.",
        imageSrc: "https://plus.unsplash.com/premium_photo-1674086970773-726e445f5802?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1172&q=80",
        imageAlt: 'Tall slender porcelain bottle with natural clay textured body and cork stopper.',
      },
    ],
    images: null,
    testimonials: null,
  },
},
{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: "Service",
  version: "v1",
  style: "CLASSIC",
  path: "index",
  data: {
    type: "Testimonial",
    id: "k",
    title: "Hero Banner!",
    subTitle: "Hero Banner Sub Title is here",
    description: "Hero Banner Paragraph is here",
    version: "v1",
    style: "CLASSIC",
    services: null,
    products: null,
    images: null,
    blogs : null,
    faqs: null,
    contactUs:null,
    portfolios: null,
    testimonials: [
      {
        id: "1",
        name: "John Doe",
        designation: "Graphic Designer",
        imageSrc: "https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(2).jpg",
        imageAlt: "Graphic Designer",
        testimonial:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac magna sit amet risus tristique interdum, at vel velit in hac habitasse platea dictumst.",
    },
    {
        id: "2",
        name: "John Doe",
        designation: "John Doe",
        imageSrc: "https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(1).jpg",
        imageAlt: "John Doe",
        testimonial:
            "Praesent placerat enim ut ex tincidunt vehicula. Fusce sit amet dui tellus. Morbi sagittis, quam nec venenatis lobortis, mi risus tempus nulla, sed porttitor est nibh at nulla.",
    },
    {
        id: "3",
        name: "John Doe",
        designation: "John Doe",
        imageSrc: "https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(9).jpg",
        imageAlt: "John Doe",
        testimonial:
            "Ut posuere, ex a fringilla hendrerit, nulla metus gravida mi, in hendrerit quam odio sed est. Vestibulum nec finibus nisi. Aliquam et ipsum nulla.",
    },
    ],
  },
},
{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: "ContactUs",
  version: "v1",
  style: "CLASSIC",
  path: "index",
  data: {
    type: "ContactUs",
    id: "k",
    title: "Get in Touch",
    subTitle: "Hero Banner Sub Title is here",
    description: "Hero Banner Paragraph is here",
    version: "v1",
    style: "CLASSIC",
    services: null,
    products: null,
    images: null,
    testimonials: null,
    faqs: null,
    portfolios: null,
    blogs : null,
    contactUs: {
      address : "Village Kimughat P.O. Garkhal, Tehsil, Kasauli, Himachal Pradesh 173201",
      email: "gayatrilodgekasauli@gmail.com",
      phone: "+91-9857315551",
    },
  },
},
{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: "Faq",
  version: "v1",
  style: "CLASSIC",
  path: "index",
  data: {
    type: "FAQ",
    id: "k",
    title: "Hero Banner!",
    subTitle: "Hero Banner Sub Title is here",
    description: "Hero Banner Paragraph is here",
    version: "v1",
    style: "CLASSIC",
    services: null,
    products: null,
    images: null,
    blogs : null,
    testimonials: null,
    portfolios: null,
    contactUs:null,
    faqs: [
      {
        id:1,
        question: 'Q.What are the check-in and check-out timings at Gayatri Lodge?',
        answer: 'Ans:The standard check-in time at Gayatri Lodge is 2:00 PM, and the check-out time is 12:00 PM (noon). However, early check-in or late check-out requests can be accommodated based on availability and may be subject to additional charges.',
      },
      {
        id:2,
        question: 'Q.What amenities are provided at Gayatri Lodge?',
        answer: 'Ans:Gayatri Lodge offers a range of amenities to make your stay comfortable. Some of the amenities include clean and well-furnished rooms, air conditioning, television, attached bathroom with hot water facility, room service, Wi-Fi access, and complimentary toiletries.',
      },
      {
        id:3,
        question: 'Q.Is there parking available at Gayatri Lodge?',
        answer: 'Ans:Yes, Gayatri Lodge provides parking facilities for guests. You can safely park your vehicle during your stay at the lodge. However, parking availability may be limited, so its advisable to inform the lodge in advance if you require parking.',
      },
      {
        id:4,
        question: 'Q.Are meals included in the room rates at Gayatri Lodge?',
        answer: 'Ans:"Yes, Gayatri Lodge provides meals as part of the room rates. Guests can enjoy delicious meals at the in-house restaurant or avail themselves of the dining options available in close proximity to the lodge. The meals offered cater to various preferences and cuisines, ensuring a satisfying dining experience for guests."',
      },
      {
        id:5,
        question: 'Q.Does Gayatri Lodge have a cancellation policy?',
        answer: 'Ans:Yes, Gayatri Lodge has a cancellation policy in place. The specific details may vary depending on the booking channel and the type of reservation made. Its advisable to review the cancellation policy at the time of booking or contact the lodge directly for more information.',
      },
      // Add more FAQs as needed
  ],
  },
},
{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: "Footer",
  version: "v1",
  style: "CLASSIC",
  path: "index",
  data: {
    type: "Footer",
    id: "k",
    title: "Hero Banner!",
    subTitle: "Hero Banner Sub Title is here",
    description: "Hero Banner Paragraph is here",
    version: "v1",
    style: "CLASSIC",
    services: null,
    products: null,
    blogs : null,
    portfolios: null,
    images: null,
    faqs: null,
    contactUs:null,
    testimonials: null,
  },
},
];

export const website3: Section[] = [
  {
      id: "69e7ed7e-889d-41c0-a1d9-62bd150401e2",
      name: "Header",
      version: "v1", // Add version property
      style: "MODERN", // Add style property
      path: "index",
      data: {
        type: "Header",
        id: "001",
        title: "HCreations",
        subTitle: "Hero Banner Sub Title is here",
        description: "Hero Banner Paragraph is here",
        version: "v1",
        style: "MODERN",
        services: null,
        products: null,
        portfolios: null,
        images: null,
        blogs : null,
        testimonials: null,
        faqs: null,
        contactUs:null,
      },
    },
{
  id: "69e7ed7e-889d-41c0-a1d9-62bd150401e2",
  name: "Herobanner",
  version: "v1", // Add version property
  style: "MODERN", // Add style property
  path: "index",
  data: {
    type: "HeroBanner",
    id: "002",
    title: "HCreations",
    subTitle: "Welcome to Handmade Creations - Customized Hampers That Fit Your Budget!",
    description: "Hero Banner Paragraph is here",
    version: "v2",
    style: "MODERN",
    services: null,
    products: null,
    images: null,
    blogs : null,
    testimonials: null,
    portfolios: null,
    faqs: null,
    contactUs:null,
  },
},
{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: " ",
  version: "v1",
  style: "CLASSIC",
  path: "index",
  data: {
    type: "Product",
    id: "k",
    title: "Our Product!",
    subTitle: "Hero Banner Sub Title is here",
    description: "Hero Banner Paragraph is here",
    version: "v1",
    style: "CLASSIC",
    services: null,
    blogs : null,
    portfolios: null,
    products: [
      {
          id: 1,
          name: 'Handcrafted Candles',
          href: '#',
          description: 'Spacious, elegant, and luxurious accommodation for ultimate comfort.',
          imageSrc: "https://www.moneymagpie.com/wp-content/uploads/2023/03/MoneyMagpie_Riverford-Christmas-Gift-Hamper.jpg.webp",
          imageAlt: 'Tall slender porcelain bottle with natural clay textured body and cork stopper.',
      },
      {
          id: 2,
          name: 'Artisanal Soaps and Bath Products',
          href: '#',
          description: 'Opulent, indulgent, and exclusive retreat for discerning guests.',
          imageSrc: "https://www.moneymagpie.com/wp-content/uploads/2023/03/MoneyMagpie_Riverford-Christmas-Gift-Hamper.jpg.webp",
          imageAlt: 'Olive drab green insulated bottle with flared screw lid and flat top.',
      },
      {
        id: 11,
        name: 'Handcrafted Candles',
        href: '#',
        description: 'Spacious, elegant, and luxurious accommodation for ultimate comfort.',
        imageSrc: "https://www.moneymagpie.com/wp-content/uploads/2023/03/MoneyMagpie_Riverford-Christmas-Gift-Hamper.jpg.webp",
        imageAlt: 'Tall slender porcelain bottle with natural clay textured body and cork stopper.',
    },
    {
        id: 21,
        name: 'Artisanal Soaps and Bath Products',
        href: '#',
        description: 'Opulent, indulgent, and exclusive retreat for discerning guests.',
        imageSrc: "https://www.moneymagpie.com/wp-content/uploads/2023/03/MoneyMagpie_Riverford-Christmas-Gift-Hamper.jpg.webp",
        imageAlt: 'Olive drab green insulated bottle with flared screw lid and flat top.',
    },
    {
      id: 122,
      name: 'Handmade Home Decor',
      href: '#',
      description: 'Spacious, elegant, and luxurious accommodation for ultimate comfort.',
      imageSrc: "https://www.moneymagpie.com/wp-content/uploads/2023/03/MoneyMagpie_Riverford-Christmas-Gift-Hamper.jpg.webp",
      imageAlt: 'Tall slender porcelain bottle with natural clay textured body and cork stopper.',
  },
  {
      id: 222,
      name: 'Artisanal Soaps and Bath Products',
      href: '#',
      description: 'Opulent, indulgent, and exclusive retreat for discerning guests.',
      imageSrc: "https://www.moneymagpie.com/wp-content/uploads/2023/03/MoneyMagpie_Riverford-Christmas-Gift-Hamper.jpg.webp",
      imageAlt: 'Olive drab green insulated bottle with flared screw lid and flat top.',
  },
      {
          id: 3,
          name: 'Gourmet Food and Treats',
          href: '#',
          description: ' Upgraded, luxurious, and lavish accommodation for a remarkable stay.',
          imageSrc: "https://www.moneymagpie.com/wp-content/uploads/2023/03/MoneyMagpie_Riverford-Christmas-Gift-Hamper.jpg.webp",
          imageAlt: 'Person using a pen to cross a task off a productivity paper card.',
      },
      // More products...
  ],
    images: null,
    faqs: null,
    testimonials: null,
    contactUs:null,
  },
},
{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: "Service",
  version: "v1",
  style: "MODERN",
  path: "index",
  data: {
    type: "AboutUs",
    id: "003",
    title: "At Handmade Creations",
    subTitle: "Hero Banner Sub Title is here",
    description: "We believe in the power of thoughtful gifting. Our passion for creativity and personalized experiences led us to establish our business, where we pour our heart and soul into curating stunning hampers that bring joy to both the giver and the recipient. \nWe understand that finding the perfect gift can be a challenge, especially when you're on a budget. That's why we've made it our mission to offer affordable yet exceptional hampers that don t compromise on quality or style. Our team of skilled artisans meticulously crafts each hamper, ensuring that every item is carefully selected and beautifully arranged.\nWe take pride in our commitment to using high-quality, locally sourced products in our hampers. From gourmet treats to luxury bath and body products, we strive to showcase the finest creations from talented artisans and small businesses.",
    version: "v1",
    style: "MODERN",
    services: null,
    products: null,
    images: null,
    blogs : null,
    testimonials: null,
    portfolios: null,
    faqs: null,
    contactUs:null,
  },
},
{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: "Service",
  version: "v1",
  style: "CLASSIC",
  path: "index",
  data: {
    type: "Testimonial",
    id: "k",
    title: "Hero Banner!",
    subTitle: "Hero Banner Sub Title is here",
    description: "Hero Banner Paragraph is here",
    version: "v1",
    style: "CLASSIC",
    services: null,
    products: null,
    images: null,
    blogs : null,
    faqs: null,
    contactUs:null,
    portfolios: null,
    testimonials: [
      {
        id: "1",
        name: "John Doe",
        designation: "Graphic Designer",
        imageSrc: "https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(2).jpg",
        imageAlt: "Graphic Designer",
        testimonial:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac magna sit amet risus tristique interdum, at vel velit in hac habitasse platea dictumst.",
    },
    {
        id: "2",
        name: "John Doe",
        designation: "John Doe",
        imageSrc: "https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(1).jpg",
        imageAlt: "John Doe",
        testimonial:
            "Praesent placerat enim ut ex tincidunt vehicula. Fusce sit amet dui tellus. Morbi sagittis, quam nec venenatis lobortis, mi risus tempus nulla, sed porttitor est nibh at nulla.",
    },
    {
        id: "3",
        name: "John Doe",
        designation: "John Doe",
        imageSrc: "https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(9).jpg",
        imageAlt: "John Doe",
        testimonial:
            "Ut posuere, ex a fringilla hendrerit, nulla metus gravida mi, in hendrerit quam odio sed est. Vestibulum nec finibus nisi. Aliquam et ipsum nulla.",
    },
    ],
  },
},
{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: "Gallery",
  version: "v1",
  style: "MODERN",
  path: "index",
  data: {
    type: "Gallery",
    id: "004",
    title: "Sample Gallery is here!",
    subTitle: "Hero Banner Sub Title is here",
    description: "Hero Banner Paragraph is here",
    version: "v1",
    style: "MODERN",
    services: null,
    products: null,
    portfolios: null,
    faqs: null,
    images: [
      {
          id: '1',
          imageSrc: 'https://www.moneymagpie.com/wp-content/uploads/2023/03/MoneyMagpie_Riverford-Christmas-Gift-Hamper.jpg.webp',
          imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
      },
      {
          id: '2',
          imageSrc: 'https://www.moneymagpie.com/wp-content/uploads/2023/03/MoneyMagpie_Riverford-Christmas-Gift-Hamper.jpg.webp',
          imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
      },
      {
          id: '3',
          imageSrc: 'https://images.unsplash.com/photo-1682695797221-8164ff1fafc9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80',
          imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
      },
      {
          id: '4',
          imageSrc: 'https://images.unsplash.com/photo-1682695797221-8164ff1fafc9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80',
          imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
      },
  ],
  blogs : null,
  testimonials: null,
  contactUs:null,
  },
},

{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: "Service",
  version: "v1",
  style: "CLASSIC",
  path: "index",
  data: {
    type: "Blog",
    id: "k",
    title: "Hero Banner!",
    subTitle: "Hero Banner Sub Title is here",
    description: "Hero Banner Paragraph is here",
    version: "v1",
    style: "CLASSIC",
    services: null,
    products: null,
    faqs: null,
    contactUs:null,
    portfolios: null,
    blogs : [
      {
        id: "1",
        title: "Blog Post 1",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        descriptionContext: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nonummy tincidunt ut lacreet dolore magna aliguam erat volutpat.",
        imageSrc: "https://www.moneymagpie.com/wp-content/uploads/2023/03/MoneyMagpie_Riverford-Christmas-Gift-Hamper.jpg.webp",
        imageAlt: 'Tall slender porcelain bottle with natural clay textured body and cork stopper.',
      },
      {
        id: "2",
        title: "Blog Post 2",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        descriptionContext: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nonummy tincidunt ut lacreet dolore magna aliguam erat volutpat.",
        imageSrc: "https://www.moneymagpie.com/wp-content/uploads/2023/03/MoneyMagpie_Riverford-Christmas-Gift-Hamper.jpg.webp",
        imageAlt: 'Tall slender porcelain bottle with natural clay textured body and cork stopper.',
      },
      {
        id: "3",
        title: "Blog Post 3",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        descriptionContext: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nonummy tincidunt ut lacreet dolore magna aliguam erat volutpat.",
        imageSrc: "https://www.moneymagpie.com/wp-content/uploads/2023/03/MoneyMagpie_Riverford-Christmas-Gift-Hamper.jpg.webp",
        imageAlt: 'Tall slender porcelain bottle with natural clay textured body and cork stopper.',
      },
      {
        id: "4",
        title: "Blog Post 3",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        descriptionContext: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nonummy tincidunt ut lacreet dolore magna aliguam erat volutpat.",
        imageSrc: "https://www.moneymagpie.com/wp-content/uploads/2023/03/MoneyMagpie_Riverford-Christmas-Gift-Hamper.jpg.webp",
        imageAlt: 'Tall slender porcelain bottle with natural clay textured body and cork stopper.',
      },
    ],
    images: null,
    testimonials: null,
  },
},

{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: "ContactUs",
  version: "v2",
  style: "CLASSIC",
  path: "index",
  data: {
    type: "ContactUs",
    id: "k",
    title: "Get in Touch",
    subTitle: "Hero Banner Sub Title is here",
    description: "Hero Banner Paragraph is here",
    version: "v2",
    style: "CLASSIC",
    services: null,
    products: null,
    images: null,
    testimonials: null,
    faqs: null,
    portfolios: null,
    blogs : null,
    contactUs: {
      address : "Village Kimughat P.O. Garkhal, Tehsil, Kasauli, Himachal Pradesh 173201",
      email: "gayatrilodgekasauli@gmail.com",
      phone: "+91-9857315551",
    },
  },
},
{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: "Footer",
  version: "v1",
  style: "CLASSIC",
  path: "index",
  data: {
    type: "Footer",
    id: "k",
    title: "Hero Banner!",
    subTitle: "Hero Banner Sub Title is here",
    description: "Hero Banner Paragraph is here",
    version: "v1",
    style: "CLASSIC",
    services: null,
    products: null,
    blogs : null,
    portfolios: null,
    images: null,
    faqs: null,
    contactUs:null,
    testimonials: null,
  },
},
];

export const basic: Section[] = [
  {
    id: "69e7ed7e-889d-41c0-a1d9-62bd150401e2",
    name: "Header",
    version: "v1", // Add version property
    style: "CLASSIC", // Add style property
    path: "index",
    data: {
      type: "ComingSoon",
      id: "001",
      title: "Comming Soon ",
      subTitle: "Hero Banner Sub Title is here",
      description: "Hero Banner Paragraph is here",
      version: "v1",
      style: "CLASSIC",
      services: null,
      products: null,
      portfolios: null,
      images: null,
      blogs : null,
      testimonials: null,
      faqs: null,
      contactUs:null,
    },
  },
];
export const pahariyatri: Section[] = [
  {
      id: "69e7ed7e-889d-41c0-a1d9-62bd150401e2",
      name: "Header",
      version: "v1", // Add version property
      style: "MODERN", // Add style property
      path: "index",
      data: {
        type: "Header",
        id: "001",
        title: "Pahari-Yatri",
        subTitle: "Hero Banner Sub Title is here",
        description: "Hero Banner Paragraph is here",
        version: "v1",
        style: "MODERN",
        services: null,
        products: null,
        portfolios: null,
        images: null,
        blogs : null,
        testimonials: null,
        faqs: null,
        contactUs:null,
      },
    },
{
  id: "69e7ed7e-889d-41c0-a1d9-62bd150401e2",
  name: "Herobanner",
  version: "v1", // Add version property
  style: "CLASSIC", // Add style property
  path: "index",
  data: {
    type: "HeroBanner",
    id: "002",
    title: "Pahari Yatri",
    subTitle: "Pahari Yatri - A Guide to Traveling on a Budget",
    description: "Hero Banner Paragraph is here",
    version: "v2",
    style: "CLASSIC",
    services: null,
    products: null,
    images: [
      {
          id: '1',
          imageSrc: 'https://images.unsplash.com/photo-1587547131116-a0655a526190?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1216&q=80',
          imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
      },
    ],
    blogs : null,
    testimonials: null,
    portfolios: null,
    faqs: null,
    contactUs:null,
  },
},
{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: " ",
  version: "v1",
  style: "CLASSIC",
  path: "index",
  data: {
    type: "Product",
    id: "k",
    title: "Our Upcoming Destination!",
    subTitle: "Join Us for a Trip to the Himalayas",
    description: "Hero Banner Paragraph is here",
    version: "v1",
    style: "CLASSIC",
    services: null,
    blogs : null,
    portfolios: null,
    products: [
      {
          id: 1,
          name: 'Roopkund Trek',
          href: '#',
          description: 'Trek to the mysterious Roopkund Lake located at an altitude of 5,029 meters (16,499 feet) in the Himalayas, known for its skeletal remains.',
          imageSrc: "https://images.unsplash.com/photo-1545652985-5edd365b12eb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
          imageAlt: 'Tall slender porcelain bottle with natural clay textured body and cork stopper.',
      },
      {
          id: 2,
          name: 'Valley of Flowers Trek',
          href: '#',
          description: 'Explore the vibrant and picturesque Valley of Flowers, a UNESCO World Heritage Site, famous for its diverse alpine flora.',
          imageSrc: "https://images.unsplash.com/photo-1564432177374-603c4ba4ee69?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1109&q=80",
          imageAlt: 'Olive drab green insulated bottle with flared screw lid and flat top.',
      },
      {
        id: 3,
        name: 'Har Ki Dun Trek',
        href: '#',
        description: 'Trek through the beautiful Har Ki Dun Valley, surrounded by snow-capped peaks, lush meadows, and traditional mountain villages.',
        imageSrc: "https://images.unsplash.com/photo-1617372155962-ba2abeaf2716?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1175&q=80",
        imageAlt: 'Tall slender porcelain bottle with natural clay textured body and cork stopper.',
      },
      {
          id: 4,
          name: 'Chadar Trek',
          href: '#',
          description: 'Embark on a unique winter trek on the frozen Zanskar River and witness the stunning frozen landscapes of the region.',
          imageSrc: "https://images.unsplash.com/photo-1542467986-13ac00f21339?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1133&q=80",
          imageAlt: 'Olive drab green insulated bottle with flared screw lid and flat top.',
      },
      {
        id: 5,
        name: 'Markha Valley Trek',
        href: '#',
        description: 'Trek through the remote Markha Valley, passing through traditional Ladakhi villages, monasteries, and stunning landscapes.',
        imageSrc: "https://images.unsplash.com/photo-1666545380082-34f26c888827?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1074&q=80",
        imageAlt: 'Tall slender porcelain bottle with natural clay textured body and cork stopper.',
      },
      {
        id: 6,
        name: 'Hampta Pass Trek',
        href: '#',
        description: 'Opulent, indulgent, and exclusive retreat for discerning guests.',
        imageSrc: "https://images.unsplash.com/photo-1520793785533-f4b11f9ae0f6?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        imageAlt: 'Olive drab green insulated bottle with flared screw lid and flat top.',
      },
      {
        id: 7,
        name: 'Goecha La Trek',
        href: '#',
        description: 'Person using a pen to cross a task off a productivity paper card.',
        imageSrc: "https://images.unsplash.com/photo-1666545381458-c9688d2d10e3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1074&q=80",
        imageAlt: 'Person using a pen to cross a task off a productivity paper card.',
      },{
        id: 8,
        name: 'Sandakphu Trek',
        href: '#',
        description: 'Trek to the highest point in West Bengal, Sandakphu, and witness panoramic views of the Himalayas, including the majestic Kanchenjunga.',
        imageSrc: "https://images.unsplash.com/photo-1520597191538-5c333fd1c980?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1249&q=80",
        imageAlt: 'Person using a pen to cross a task off a productivity paper card.',
      },{
        id: 9,
        name: 'Vellay of flowers ',
        href: '#',
        description: 'Explore the vibrant and picturesque Valley of Flowers, a UNESCO World Heritage Site, famous for its diverse alpine flora.',

        imageSrc: "https://images.unsplash.com/photo-1666545378647-e7eeb3ca61a5?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1074&q=80",
        imageAlt: 'Person using a pen to cross a task off a productivity paper card.',
      },
      // More products...
  ],
    images: null,
    faqs: null,
    testimonials: null,
    contactUs:null,
  },
},
{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: "About-Us",
  version: "v1",
  style: "CLASSIC",
  path: "index",
  data: {
    type: "AboutUs",
    id: "003",
    title: "About Pahari Yatri",
    subTitle: "Hero Banner Sub Title is here",
    description: "At Pahari Yatri, we are passionate about providing exhilarating trekking and mountaineering experiences that connect individuals with nature's breathtaking beauty. As a leading adventure travel company, we specialize in curating personalized adventures, ensuring the highest safety standards, and promoting sustainable tourism practices. Our team of experienced professionals is committed to creating unforgettable memories for every adventurer who embarks on a journey with us.",
    version: "v1",
    style: "CLASSIC",
    services: null,
    products: null,
    images: [
      {
          id: '1',
          imageSrc: 'https://images.unsplash.com/photo-1545652985-5edd365b12eb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80',
          imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
      },
    ],
    blogs : null,
    testimonials: null,
    portfolios: null,
    faqs: null,
    contactUs:null,
  },
},
{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: "Gallery",
  version: "v1",
  style: "MODERN",
  path: "index",
  data: {
    type: "Gallery",
    id: "004",
    title: "Sample Gallery is here!",
    subTitle: "Hero Banner Sub Title is here",
    description: "Hero Banner Paragraph is here",
    version: "v1",
    style: "MODERN",
    services: null,
    products: null,
    portfolios: null,
    faqs: null,
    images: [
      {
          id: '1',
          imageSrc: 'https://www.moneymagpie.com/wp-content/uploads/2023/03/MoneyMagpie_Riverford-Christmas-Gift-Hamper.jpg.webp',
          imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
      },
      {
          id: '2',
          imageSrc: 'https://www.moneymagpie.com/wp-content/uploads/2023/03/MoneyMagpie_Riverford-Christmas-Gift-Hamper.jpg.webp',
          imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
      },
      {
          id: '3',
          imageSrc: 'https://images.unsplash.com/photo-1682695797221-8164ff1fafc9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80',
          imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
      },
      {
          id: '4',
          imageSrc: 'https://images.unsplash.com/photo-1682695797221-8164ff1fafc9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80',
          imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
      },
  ],
  blogs : null,
  testimonials: null,
  contactUs:null,
  },
},

{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: "Service",
  version: "v1",
  style: "CLASSIC",
  path: "index",
  data: {
    type: "Service",
    id: "k",
    title: "Our Services",
    subTitle: "Hero Banner Sub Title is here",
    description: "We are provided following services to our customers",
    version: "v1",
    style: "CLASSIC",
    blogs : null,
    faqs: null,
    contactUs:null,
    portfolios: null,
    services: [
      {
          id: 1,
          title: 'Trekking',
          body: 'Unleash your inner adventurer on thrilling trekking trails. Explore diverse landscapes, ancient trails, and remote valleys with our experienced guides.',
          imageSrc: 'https://htmldemo.zcubethemes.com/riorelax/img/icon/sve-icon3.png',
          imageAlt: 'parking icon',
      },
      {
          id: 2,
          title: 'Camping',
          body: 'Embrace nature s tranquility in picturesque camping spots. Disconnect from the world and reconnect with the wilderness under starry skies.',
          imageSrc: 'https://htmldemo.zcubethemes.com/riorelax/img/icon/fe-icon01.png',
          imageAlt: 'parking icon',
      },
      {
          id: 3,
          title: 'Adventure Tours',
          body: 'Combine adrenaline-pumping activities with cultural immersions. Encounter wildlife, explore diverse terrains, and immerse in local traditions.',
          imageSrc: 'https://htmldemo.zcubethemes.com/riorelax/img/icon/sve-icon2.png',
          imageAlt: 'parking icon',
      },
      {
          id: 4,
          title: 'Cultural Immersion',
          body: 'Immerse in the richness of local cultures. Participate in traditions, savor authentic cuisines, and gain a deeper understanding of customs.',
          imageSrc: 'https://htmldemo.zcubethemes.com/riorelax/img/icon/fe-icon08.png',
          imageAlt: 'parking icon',
      },
      {
          id: 5,
          title: 'Safety First',
          body: 'Your safety is our priority. We adhere to rigorous safety protocols to ensure secure and enriching experiences.',
          imageSrc: 'https://htmldemo.zcubethemes.com/riorelax/img/icon/fe-icon05.png',
          imageAlt: 'parking icon',
      },
      {
          id: 6,
          title: 'Mountaineering',
          body: 'Conquer peaks with expert guidance and safety measures. From challenging expeditions to less technical climbs, we cater to all levels of mountaineering enthusiasts.',
          imageSrc: 'https://htmldemo.zcubethemes.com/riorelax/img/icon/fe-icon05.png',
          imageAlt: 'parking icon',
      },
    ],
    products: null,
    images: null,
    testimonials: null,
  },
},

{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: "Blog",
  version: "v1",
  style: "CLASSIC",
  path: "index",
  data: {
    type: "Blog",
    id: "k",
    title: "Hero Banner!",
    subTitle: "Hero Banner Sub Title is here",
    description: "Hero Banner Paragraph is here",
    version: "v1",
    style: "CLASSIC",
    services: null,
    products: null,
    faqs: null,
    contactUs:null,
    portfolios: null,
    blogs : [
      {
        id: "1",
        title: "Har Ki Dun Trek",
        description: 'Trek through the beautiful Har Ki Dun Valley, surrounded by snow-capped peaks, lush meadows, and traditional mountain villages.',
        descriptionContext: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nonummy tincidunt ut lacreet dolore magna aliguam erat volutpat.",
        imageSrc: "https://images.unsplash.com/photo-1545652985-5edd365b12eb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        imageAlt: 'Tall slender porcelain bottle with natural clay textured body and cork stopper.',
      },
      {
        id: "2",
        title: "Great Lakes Trek",
        description: 'Explore the pristine alpine lakes of the Kashmir region, including Vishansar Lake, Gadsar Lake, and Nundkol Lake.',
        descriptionContext: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nonummy tincidunt ut lacreet dolore magna aliguam erat volutpat.",
        imageSrc: "https://images.unsplash.com/photo-1526772662000-3f88f10405ff?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1074&q=80",
        imageAlt: 'Tall slender porcelain bottle with natural clay textured body and cork stopper.',
      },
      {
        id: "3",
        title: "Sandakphu Trek",
        description: 'Trek to the highest point in West Bengal, Sandakphu, and witness panoramic views of the Himalayas, including the majestic Kanchenjunga.',
        descriptionContext: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nonummy tincidunt ut lacreet dolore magna aliguam erat volutpat.",
        imageSrc: "https://images.unsplash.com/photo-1523341139367-9de570b874ed?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        imageAlt: 'Tall slender porcelain bottle with natural clay textured body and cork stopper.',
      },
      {
        id: "4",
        title: "Hampta Pass Trek",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        descriptionContext: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nonummy tincidunt ut lacreet dolore magna aliguam erat volutpat.",
        imageSrc: "https://images.unsplash.com/photo-1520982184827-6950930eaf2b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        imageAlt: 'Tall slender porcelain bottle with natural clay textured body and cork stopper.',
      },
    ],
    images: null,
    testimonials: null,
  },
},

{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: "ContactUs",
  version: "v2",
  style: "CLASSIC",
  path: "index",
  data: {
    type: "ContactUs",
    id: "k",
    title: "Get in Touch",
    subTitle: "Contact Us Sub Title is here",
    description: "Hero Banner Paragraph is here",
    version: "v2",
    style: "CLASSIC",
    services: null,
    products: null,
    images: null,
    testimonials: null,
    faqs: null,
    portfolios: null,
    blogs : null,
    contactUs: {
      address : "Village Kimughat P.O. Garkhal, Tehsil, Kasauli, Himachal Pradesh 173201",
      email: "gayatrilodgekasauli@gmail.com",
      phone: "+91-9857315551",
    },
  },
},
{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: "Footer",
  version: "v1",
  style: "CLASSIC",
  path: "index",
  data: {
    type: "Footer",
    id: "k",
    title: "Hero Banner!",
    subTitle: "Hero Banner Sub Title is here",
    description: "Hero Banner Paragraph is here",
    version: "v1",
    style: "CLASSIC",
    services: null,
    products: null,
    blogs : null,
    portfolios: null,
    images: null,
    faqs: null,
    contactUs:null,
    testimonials: null,
  },
},
];
export const gayatrilodge: Section[] = [
  {
      id: "69e7ed7e-889d-41c0-a1d9-62bd150401e2",
      name: "Header",
      version: "v1", // Add version property
      style: "CLASSIC", // Add style property
      path: "index",
      data: {
        type: "Header",
        id: "001",
        title: "Gayatri Lodge",
        subTitle: "Hero Banner Sub Title is",
        description: "Hero Banner Paragraph is here",
        version: "v1",
        style: "CLASSIC",
        services: null,
        products: null,
        portfolios: null,
        images: null,
        blogs : null,
        testimonials: null,
        faqs: null,
        contactUs:null,
      },
    },

{
  id: "69e7ed7e-889d-41c0-a1d9-62bd150401e2",
  name: "Herobanner",
  version: "v1", // Add version property
  style: "CLASSIC", // Add style property
  path: "index",
  data: {
    type: "HeroBanner",
    id: "002",
    title: "Gayatri Lodge!",
    subTitle: "Welcome to Gayatri Lodge, Your Tranquil Haven in Kasauli",
    description: "Hero Banner Paragraph is here",
    version: "v1",
    style: "CLASSIC",
    services: null,
    products: null,
    images: [
      {
        id: '1',
        imageSrc: 'https://images.unsplash.com/photo-1597256817041-0c75c0633658?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=849&q=80',
        imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
      },
    ],
    portfolios: null,
    blogs : null,
    testimonials: null,
    faqs: null,
    contactUs:null,
  },
},
{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: "Service",
  version: "v1",
  style: "CLASSIC",
  path: "index",
  data: {
    type: "AboutUs",
    id: "003",
    title: "About us!",
    subTitle: "Hero Banner Sub Title is here",
    description: "At Gayatri Lodge, we believe in creating unforgettable memories for our guests. As a family-owned homestay, we take pride in our personalized approach and attention to detail. With years of experience in hospitality, we have curated a haven where every guest is treated like a part of our extended family. Our warm and friendly staff is dedicated to ensuring your stay is nothing short of exceptional.",
    version: "v1",
    style: "CLASSIC",
    services: null,
    products: null,
    portfolios: null,
    images: [
      {
        id: '1',
        imageSrc: 'https://images.unsplash.com/photo-1597256817041-0c75c0633658?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=849&q=80',
        imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
      },
    ],
    blogs : null,
    testimonials: null,
    faqs: null,
    contactUs:null,
  },
},
{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: "Gallery",
  version: "v1",
  style: "CLASSIC",
  path: "index",
  data: {
    type: "Gallery",
    id: "004",
    title: "Our Gallery !",
    subTitle: "Hero Banner Sub Title is here",
    description: "Hero Banner Paragraph is here",
    version: "v1",
    style: "CLASSIC",
    services: null,
    products: null,
    portfolios: null,
    faqs: null,
    images: [
      {
          id: '1',
          imageSrc: 'https://tailwindui.com/img/ecommerce-images/home-page-02-edition-01.jpg',
          imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
      },
      {
          id: '2',
          imageSrc: 'https://images.unsplash.com/photo-1684752097893-13785863f9a1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=435&q=80',
          imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
      },
      {
          id: '3',
          imageSrc: 'https://images.unsplash.com/photo-1682695797221-8164ff1fafc9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80',
          imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
      },
      {
          id: '4',
          imageSrc: 'https://images.unsplash.com/photo-1682695797221-8164ff1fafc9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80',
          imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
      },
  ],
  blogs : null,
  testimonials: null,
  contactUs:null,
  },
},
{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: " ",
  version: "v1",
  style: "CLASSIC",
  path: "index",
  data: {
    type: "Product",
    id: "k",
    title: "Our Rooms!",
    subTitle: "Hero Banner Sub Title is here",
    description: "Hero Banner Paragraph is here",
    version: "v1",
    style: "CLASSIC",
    services: null,
    blogs : null,
    portfolios: null,
    products: [
      {
          id: 1,
          name: 'Deluxe Room',
          href: '#',
          description: 'Spacious, elegant, and luxurious accommodation for ultimate comfort.',
          imageSrc: "https://images.unsplash.com/photo-1611892440504-42a792e24d32?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
          imageAlt: 'Tall slender porcelain bottle with natural clay textured body and cork stopper.',
      },
      {
          id: 2,
          name: 'Master Room',
          href: '#',
          description: 'Opulent, indulgent, and exclusive retreat for discerning guests.',
          imageSrc: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80",
          imageAlt: 'Olive drab green insulated bottle with flared screw lid and flat top.',
      },
      {
          id: 3,
          name: 'Super Room',
          href: '#',
          description: ' Upgraded, luxurious, and lavish accommodation for a remarkable stay.',
          imageSrc: "https://images.unsplash.com/photo-1618773928121-c32242e63f39?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
          imageAlt: 'Person using a pen to cross a task off a productivity paper card.',
      },
      {
          id: 4,
          name: 'Normal Room',
          href: '#',
          description: 'Comfortable, affordable, and practical choice for a pleasant stay.',
          imageSrc: "https://images.unsplash.com/photo-1591088398332-8a7791972843?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1074&q=80",
          imageAlt: 'Hand holding black machined steel mechanical pencil with brass tip and top.',
      },
      // More products...
  ],
    images: null,
    faqs: null,
    testimonials: null,
    contactUs:null,
  },
},
{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: "Service",
  version: "v1",
  style: "CLASSIC",
  path: "index",
  data: {
    type: "Service",
    id: "k",
    title: "Our Services",
    subTitle: "Hero Banner Sub Title is here",
    description: "Hero Banner Paragraph is here",
    version: "v1",
    style: "CLASSIC",
    blogs : null,
    faqs: null,
    contactUs:null,
    portfolios: null,
    services: [
      {
          id: 1,
          title: 'Parking Space',
          body: 'We dejoy working with discerning clients, people for whom qualuty, service, integrity & aesthetics.',
          imageSrc: 'https://htmldemo.zcubethemes.com/riorelax/img/icon/sve-icon3.png',
          imageAlt: 'parking icon',
      },
      {
          id: 2,
          title: 'Room Service',
          body: 'We dejoy working with discerning clients, people for whom qualuty, service, integrity & aesthetics.',
          imageSrc: 'https://htmldemo.zcubethemes.com/riorelax/img/icon/fe-icon01.png',
          imageAlt: 'parking icon',
      },
      {
          id: 3,
          title: 'Fibre Internet',
          body: 'We dejoy working with discerning clients, people for whom qualuty, service, integrity & aesthetics.',
          imageSrc: 'https://htmldemo.zcubethemes.com/riorelax/img/icon/sve-icon2.png',
          imageAlt: 'parking icon',
      },
      {
          id: 4,
          title: 'Special Offers',
          body: 'We dejoy working with discerning clients, people for whom qualuty, service, integrity & aesthetics.',
          imageSrc: 'https://htmldemo.zcubethemes.com/riorelax/img/icon/fe-icon08.png',
          imageAlt: 'parking icon',
      },
      {
          id: 5,
          title: 'Best Accommodation',
          body: 'We dejoy working with discerning clients, people for whom qualuty, service, integrity & aesthetics.',
          imageSrc: 'https://htmldemo.zcubethemes.com/riorelax/img/icon/fe-icon05.png',
          imageAlt: 'parking icon',
      },
      {
          id: 6,
          title: 'Breakfast',
          body: 'We dejoy working with discerning clients, people for whom qualuty, service, integrity & aesthetics.',
          imageSrc: 'https://htmldemo.zcubethemes.com/riorelax/img/icon/fe-icon05.png',
          imageAlt: 'parking icon',
      },
    ],
    products: null,
    images: null,
    testimonials: null,
  },
},
{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: "Service",
  version: "v1",
  style: "CLASSIC",
  path: "index",
  data: {
    type: "Blog",
    id: "k",
    title: "Hero Banner!",
    subTitle: "Hero Banner Sub Title is here",
    description: "Hero Banner Paragraph is here",
    version: "v1",
    style: "CLASSIC",
    services: null,
    products: null,
    faqs: null,
    contactUs:null,
    portfolios: null,
    blogs : [
      {
        id: "1",
        title: "Blog Post 1",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        descriptionContext: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nonummy tincidunt ut lacreet dolore magna aliguam erat volutpat.",
        imageSrc: "https://images.unsplash.com/photo-1591088398332-8a7791972843?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1074&q=80",
        imageAlt: 'Tall slender porcelain bottle with natural clay textured body and cork stopper.',
      },
      {
        id: "2",
        title: "Blog Post 2",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        descriptionContext: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nonummy tincidunt ut lacreet dolore magna aliguam erat volutpat.",
        imageSrc: "https://images.unsplash.com/photo-1591088398332-8a7791972843?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1074&q=80",
        imageAlt: 'Tall slender porcelain bottle with natural clay textured body and cork stopper.',
      },
      {
        id: "3",
        title: "Blog Post 3",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        descriptionContext: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nonummy tincidunt ut lacreet dolore magna aliguam erat volutpat.",
        imageSrc: "https://images.unsplash.com/photo-1591088398332-8a7791972843?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1074&q=80",
        imageAlt: 'Tall slender porcelain bottle with natural clay textured body and cork stopper.',
      },
      {
        id: "4",
        title: "Blog Post 3",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        descriptionContext: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nonummy tincidunt ut lacreet dolore magna aliguam erat volutpat.",
        imageSrc: "https://images.unsplash.com/photo-1591088398332-8a7791972843?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1074&q=80",
        imageAlt: 'Tall slender porcelain bottle with natural clay textured body and cork stopper.',
      },
    ],
    images: null,
    testimonials: null,
  },
},
{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: "Service",
  version: "v1",
  style: "CLASSIC",
  path: "index",
  data: {
    type: "Testimonial",
    id: "k",
    title: "Hero Banner!",
    subTitle: "Hero Banner Sub Title is here",
    description: "Hero Banner Paragraph is here",
    version: "v1",
    style: "CLASSIC",
    services: null,
    products: null,
    images: null,
    blogs : null,
    portfolios: null,
    faqs: null,
    contactUs:null,
    testimonials: [
      {
        id: "1",
        name: "John Doe",
        designation: "Graphic Designer",
        imageSrc: "https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(2).jpg",
        imageAlt: "Graphic Designer",
        testimonial:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac magna sit amet risus tristique interdum, at vel velit in hac habitasse platea dictumst.",
    },
    {
        id: "2",
        name: "John Doe",
        designation: "John Doe",
        imageSrc: "https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(1).jpg",
        imageAlt: "John Doe",
        testimonial:
            "Praesent placerat enim ut ex tincidunt vehicula. Fusce sit amet dui tellus. Morbi sagittis, quam nec venenatis lobortis, mi risus tempus nulla, sed porttitor est nibh at nulla.",
    },
    {
        id: "3",
        name: "John Doe",
        designation: "John Doe",
        imageSrc: "https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(9).jpg",
        imageAlt: "John Doe",
        testimonial:
            "Ut posuere, ex a fringilla hendrerit, nulla metus gravida mi, in hendrerit quam odio sed est. Vestibulum nec finibus nisi. Aliquam et ipsum nulla.",
    },
    ],
  },
},
{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: "ContactUs",
  version: "v1",
  style: "CLASSIC",
  path: "index",
  data: {
    type: "ContactUs",
    id: "k",
    title: "Get in Touch",
    subTitle: "Hero Banner Sub Title is here",
    description: "Hero Banner Paragraph is here",
    version: "v1",
    style: "CLASSIC",
    services: null,
    products: null,
    images: null,
    testimonials: null,
    faqs: null,
    blogs : null,
    portfolios: null,
    contactUs: {
      address : "Village Kimughat P.O. Garkhal, Tehsil, Kasauli, Himachal Pradesh 173201",
      email: "gayatrilodgekasauli@gmail.com",
      phone: "+91-9857315551",
    },
  },
},
{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: "Faq",
  version: "v1",
  style: "CLASSIC",
  path: "index",
  data: {
    type: "FAQ",
    id: "k",
    title: "Hero Banner!",
    subTitle: "Hero Banner Sub Title is here",
    description: "Hero Banner Paragraph is here",
    version: "v1",
    style: "CLASSIC",
    services: null,
    products: null,
    images: null,
    blogs : null,
    testimonials: null,
    portfolios: null,
    contactUs:null,
    faqs: [
      {
        id:1,
        question: 'Q.What are the check-in and check-out timings at Gayatri Lodge?',
        answer: 'Ans:The standard check-in time at Gayatri Lodge is 2:00 PM, and the check-out time is 12:00 PM (noon). However, early check-in or late check-out requests can be accommodated based on availability and may be subject to additional charges.',
      },
      {
        id:2,
        question: 'Q.What amenities are provided at Gayatri Lodge?',
        answer: 'Ans:Gayatri Lodge offers a range of amenities to make your stay comfortable. Some of the amenities include clean and well-furnished rooms, air conditioning, television, attached bathroom with hot water facility, room service, Wi-Fi access, and complimentary toiletries.',
      },
      {
        id:3,
        question: 'Q.Is there parking available at Gayatri Lodge?',
        answer: 'Ans:Yes, Gayatri Lodge provides parking facilities for guests. You can safely park your vehicle during your stay at the lodge. However, parking availability may be limited, so its advisable to inform the lodge in advance if you require parking.',
      },
      {
        id:4,
        question: 'Q.Are meals included in the room rates at Gayatri Lodge?',
        answer: 'Ans:"Yes, Gayatri Lodge provides meals as part of the room rates. Guests can enjoy delicious meals at the in-house restaurant or avail themselves of the dining options available in close proximity to the lodge. The meals offered cater to various preferences and cuisines, ensuring a satisfying dining experience for guests."',
      },
      {
        id:5,
        question: 'Q.Does Gayatri Lodge have a cancellation policy?',
        answer: 'Ans:Yes, Gayatri Lodge has a cancellation policy in place. The specific details may vary depending on the booking channel and the type of reservation made. Its advisable to review the cancellation policy at the time of booking or contact the lodge directly for more information.',
      },
      // Add more FAQs as needed
  ],
  },
},
{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: "Footer",
  version: "v1",
  style: "CLASSIC",
  path: "index",
  data: {
    type: "Footer",
    id: "k",
    title: "Hero Banner!",
    subTitle: "Hero Banner Sub Title is here",
    description: "Hero Banner Paragraph is here",
    version: "v1",
    style: "CLASSIC",
    services: null,
    products: null,
    portfolios: null,
    blogs : null,
    images: null,
    faqs: null,
    contactUs:null,
    testimonials: null,
  },
},
];

export const techie: Section[] = [
  {
    id: "69e7ed7e-889d-41c0-a1d9-62bd150401e2",
    name: "Header",
    version: "v1", // Add version property
    style: "CLASSIC", // Add style property
    path: "index",
    data: {
      type: "Header",
      id: "001",
      title: "Portfolio",
      subTitle: "Hero Banner Sub Title is",
      description: "Hero Banner Paragraph is here",
      version: "v1",
      style: "CLASSIC",
      services: null,
      products: null,
      portfolios: null,
      images: null,
      blogs : null,
      testimonials: null,
      faqs: null,
      contactUs:null,
    },
  },
  {
    id: "69e7ed7e-889d-41c0-a1d9-62bd150401e2",
    name: "Herobanner",
    version: "v1", // Add version property
    style: "CLASSIC", // Add style property
    path: "index",
    data: {
      type: "HeroBanner",
      id: "002",
      title: "Pahari Yatri",
      subTitle: "Pahari Yatri - A Guide to Traveling on a Budget",
      description: "Hero Banner Paragraph is here",
      version: "v2",
      style: "CLASSIC",
      services: null,
      products: null,
      images: [
        {
            id: '1',
            imageSrc: 'https://images.unsplash.com/photo-1571171637578-41bc2dd41cd2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80',
            imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
        },
      ],
      blogs : null,
      testimonials: null,
      portfolios: null,
      faqs: null,
      contactUs:null,
    },
  },
  {
    id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
    name: "Footer",
    version: "v1",
    style: "CLASSIC",
    path: "index",
    data: {
      type: "Footer",
      id: "k",
      title: "Hero Banner!",
      subTitle: "Hero Banner Sub Title is here",
      description: "Hero Banner Paragraph is here",
      version: "v1",
      style: "CLASSIC",
      services: null,
      products: null,
      portfolios: null,
      blogs : null,
      images: null,
      faqs: null,
      contactUs:null,
      testimonials: null,
    },
  },
];

export const blogpahariyatri: Section[] = [
  {
    id: "69e7ed7e-889d-41c0-a1d9-62bd150401e2",
    name: "Header",
    version: "v1", // Add version property
    style: "CLASSIC", // Add style property
    path: "index",
    data: {
      type: "Header",
      id: "001",
      title: "Blog",
      subTitle: "Hero Banner Sub Title is",
      description: "Hero Banner Paragraph is here",
      version: "v1",
      style: "CLASSIC",
      services: null,
      products: null,
      portfolios: null,
      images: null,
      blogs : null,
      testimonials: null,
      faqs: null,
      contactUs:null,
    },
  },
  {
    id: "69e7ed7e-889d-41c0-a1d9-62bd150401e2",
    name: "Herobanner",
    version: "v1", // Add version property
    style: "CLASSIC", // Add style property
    path: "index",
    data: {
      type: "HeroBanner",
      id: "002",
      title: "Pahari Yatri",
      subTitle: "Pahari Yatri - A Guide to Traveling on a Budget",
      description: "Hero Banner Paragraph is here",
      version: "v2",
      style: "CLASSIC",
      services: null,
      products: null,
      images: [
        {
            id: '1',
            imageSrc: 'https://images.unsplash.com/photo-1587547131116-a0655a526190?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1216&q=80',
            imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
        },
      ],
      blogs : null,
      testimonials: null,
      portfolios: null,
      faqs: null,
      contactUs:null,
    },
  },
  {
    id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
    name: "Blog",
    version: "v1",
    style: "CLASSIC",
    path: "index",
    data: {
      type: "Blog",
      id: "k",
      title: "Hero Banner!",
      subTitle: "Hero Banner Sub Title is here",
      description: "Hero Banner Paragraph is here",
      version: "v1",
      style: "CLASSIC",
      services: null,
      products: null,
      faqs: null,
      contactUs:null,
      portfolios: null,
      blogs : [
        {
          id: "1",
          title: "Hampta Pass Trek: A Journey from Green to Snow",
          description: 'Embark on a captivating adventure from the lush green valleys of Kullu to the snow-clad wonderland of Spiti. Discover the magic of Hampta Pass and its breathtaking vistas in this unforgettable blog.',
          descriptionContext: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nonummy tincidunt ut lacreet dolore magna aliguam erat volutpat.",
          imageSrc: "https://images.unsplash.com/photo-1656833111546-07d98abab448?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
          imageAlt: 'Tall slender porcelain bottle with natural clay textured body and cork stopper.',
        },
        {
          id: "2",
          title: "Roopkund Trek: Unraveling the Mystery of Skeleton Lake",
          description: 'Join us as we venture into the enigmatic world of Roopkund. Delve into the legend, history, and natural beauty surrounding this mystical lake in our thrilling blog.',
          descriptionContext: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nonummy tincidunt ut lacreet dolore magna aliguam erat volutpat.",
          imageSrc: "https://images.unsplash.com/photo-1545652985-5edd365b12eb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
          imageAlt: 'Tall slender porcelain bottle with natural clay textured body and cork stopper.',
        },
        {
          id: "3",
          title: "Valley of Flowers Trek: A Kaleidoscope of Colors",
          description: 'Immerse yourself in the kaleidoscope of colors as we explore the stunning Valley of Flowers. Discover the unique flora and fauna that make this trek a once-in-a-lifetime experience.',
          descriptionContext: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nonummy tincidunt ut lacreet dolore magna aliguam erat volutpat.",
          imageSrc: "https://images.unsplash.com/photo-1564432177374-603c4ba4ee69?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1109&q=80",
          imageAlt: 'Tall slender porcelain bottle with natural clay textured body and cork stopper.',
        },
        {
          id: "4",
          title: "Har Ki Dun Trek: A Divine Sojourn in the Valley of Gods",
          description: "Follow our footsteps into the mystical Har Ki Dun Valley, where nature's beauty meets divine serenity. Read about our encounters with local culture and the enchanting landscapes in this captivating blog.",
          descriptionContext: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nonummy tincidunt ut lacreet dolore magna aliguam erat volutpat.",
          imageSrc: "https://images.unsplash.com/photo-1520982184827-6950930eaf2b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
          imageAlt: 'Tall slender porcelain bottle with natural clay textured body and cork stopper.',
        },{
          id: "5",
          title: "Kedarkantha Trek: A Winter Wonderland in the Himalayas",
          description: "Embark on a winter wonderland adventure as we trek to the summit of Kedarkantha. Join us as we unravel the charm of this snow-laden trek and its mesmerizing panoramas.",
          descriptionContext: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nonummy tincidunt ut lacreet dolore magna aliguam erat volutpat.",
          imageSrc: "https://images.unsplash.com/photo-1520982184827-6950930eaf2b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
          imageAlt: 'Tall slender porcelain bottle with natural clay textured body and cork stopper.',
        },{
          id: "6",
          title: "Deoriatal Chandrashila Trek: A Spiritual Journey to the Heights",
          description: "Walk with us on a spiritual journey to the heights of Chandrashila. Discover the beauty of Deoriatal Lake and the spiritual essence of this trek in our insightful blog.",
          descriptionContext: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nonummy tincidunt ut lacreet dolore magna aliguam erat volutpat.",
          imageSrc: "https://images.unsplash.com/photo-1520982184827-6950930eaf2b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
          imageAlt: 'Tall slender porcelain bottle with natural clay textured body and cork stopper.',
        },{
          id: "7",
          title: "Bhrigu Lake Trek: Amidst the Shimmering Waters and High Peaks",
          description: "Discover the enchanting Bhrigu Lake, nestled amidst the shimmering waters and towering peaks. Join us on this offbeat trek and witness nature's splendor.",
          descriptionContext: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nonummy tincidunt ut lacreet dolore magna aliguam erat volutpat.",
          imageSrc: "https://images.unsplash.com/photo-1520982184827-6950930eaf2b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
          imageAlt: 'Tall slender porcelain bottle with natural clay textured body and cork stopper.',
        },{
          id: "8",
          title: "Nag Tibba Trek: Unraveling the Hidden Gem of Garhwal",
          description: " Unravel the hidden gem of Garhwal as we trek to the Nag Tibba summit. Delight in panoramic views, dense forests, and a glimpse of the snow-capped Himalayas.",
          descriptionContext: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nonummy tincidunt ut lacreet dolore magna aliguam erat volutpat.",
          imageSrc: "https://images.unsplash.com/photo-1520982184827-6950930eaf2b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
          imageAlt: 'Tall slender porcelain bottle with natural clay textured body and cork stopper.',
        },{
          id: "9",
          title: "Beas Kund Trek: Tracing the Source of River Beas",
          description: "Trace the source of the mighty Beas River on the Beas Kund Trek. Walk through alpine meadows, glaciers, and pristine landscapes in this awe-inspiring journey.",
          descriptionContext: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nonummy tincidunt ut lacreet dolore magna aliguam erat volutpat.",
          imageSrc: "https://images.unsplash.com/photo-1520982184827-6950930eaf2b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
          imageAlt: 'Tall slender porcelain bottle with natural clay textured body and cork stopper.',
        },
      ],
      images: null,
      testimonials: null,
    },
  },
  {
    id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
    name: "Footer",
    version: "v1",
    style: "CLASSIC",
    path: "index",
    data: {
      type: "Footer",
      id: "k",
      title: "Hero Banner!",
      subTitle: "Hero Banner Sub Title is here",
      description: "Hero Banner Paragraph is here",
      version: "v1",
      style: "CLASSIC",
      services: null,
      products: null,
      portfolios: null,
      blogs : null,
      images: null,
      faqs: null,
      contactUs:null,
      testimonials: null,
    },
  },
];
