import { PluginConfig } from "../modal/PluginConfig";
import { Section } from "../modal/Section";

export const drayWorldLogisticTheme: any = {
    name: "vibrant"
}

export const drayWorldLogistic: Section[] = [
    {
        id: "69e7ed7e-889d-41c0-a1d9-62bd150401e2",
        name: "Header",
        version: "v2",
        style: "MODERN",
        path: "index",
        data: {
            type: "Header",
            id: "001",
            title: "Dray World Logistics",
            subTitle: "Your Reliable Logistics Partner",
            description: "We Deliver Excellence",
            version: "v2",
            style: "MODERN",
            services: null,
            products: null,
            portfolios: null,
            images: [
                {
                    id: '1',
                    imageSrc: 'https://i.pinimg.com/564x/8e/e4/24/8ee424ad844db2c4a48673616f42302f.jpg',
                    imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
                },
            ],
            blogs: null,
            testimonials: null,
            faqs: null,
            contactUs: {
                address: "",
                email: "info@drayworldlogistics.com",
                phone: "123-456-7890",
            },
        },
    },
    {
        id: "69e7ed7e-889d-41c0-a1d9-62bd150401e2",
        name: "Hero Banner",
        version: "v1",
        style: "CLASSIC",
        path: "index",
        data: {
            type: "HeroBanner",
            id: "002",
            title: "Logistics Solutions",
            subTitle: "Your Cargo, Our Priority",
            description: "Efficient, Secure, and Reliable",
            version: "v2",
            style: "CLASSIC",
            services: null,
            products: null,
            images: [
                {
                    id: '1',
                    imageSrc: 'https://images.unsplash.com/photo-1513932961238-391bf5dff447?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80',
                    imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
                },
            ],
            blogs: null,
            testimonials: null,
            portfolios: null,
            faqs: null,
            contactUs: null,
        },
    },
    {
        id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
        name: "About Us",
        version: "v1",
        style: "CLASSIC",
        path: "index",
        data: {
            type: "AboutUs",
            id: "003",
            title: "About Dray World Logistics",
            subTitle: "Your Trusted Logistics Partner",
            description: "At Dray World Logistics, we are dedicated to providing specialized logistics services that ensure the secure and efficient transportation of your cargo. With years of experience and a commitment to excellence, we are your reliable logistics partner.",
            version: "v1",
            style: "CLASSIC",
            services: null,
            products: null,
            images: [
                {
                    id: '1',
                    imageSrc: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1784&q=80',
                    imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
                },
            ],
            blogs: null,
            testimonials: null,
            portfolios: null,
            faqs: null,
            contactUs: null,
        },
    },
    {
        id: "Service",
        name: "Service",
        version: "v1",
        style: "CLASSIC",
        path: "index",
        data: {
            type: "Service",
            id: "k",
            title: "Our Logistics Services",
            subTitle: "Efficient Cargo Transportation",
            description: "Explore our comprehensive logistics services that ensure the secure and timely transportation of your cargo. Your logistics needs, our expertise.",
            version: "v2",
            style: "CLASSIC",
            blogs: null,
            faqs: null,
            contactUs: null,
            portfolios: null,
            services: [
                {
                    id: 1,
                    title: 'Freight Forwarding',
                    body: 'Efficient cargo forwarding services tailored to your specific needs.',
                    imageSrc: '',
                    imageAlt: 'Freight Forwarding Icon',
                },
                {
                    id: 2,
                    title: 'Warehousing',
                    body: 'Safe and secure warehousing solutions for your goods.',
                    imageSrc: '',
                    imageAlt: 'Warehousing Icon',
                },
                {
                    id: 3,
                    title: 'Customs Clearance',
                    body: 'Expert customs clearance services to streamline international shipments.',
                    imageSrc: '',
                    imageAlt: 'Customs Clearance Icon',
                },
                {
                    id: 4,
                    title: 'Last-Mile Delivery',
                    body: 'Efficient last-mile delivery services for a seamless customer experience.',
                    imageSrc: '',
                    imageAlt: 'Last-Mile Delivery Icon',
                },
            ],
            products: null,
            images: null,
            testimonials: null,
        },
    },
    {
        id: "69e7ed7e-889d-41c0-a1d9-62bd150401e2",
        name: "Hero Banner",
        version: "v1",
        style: "CLASSIC",
        path: "index",
        data: {
            type: "HeroBanner",
            id: "002",
            title: "Logistics Solutions",
            subTitle: "Your Cargo, Our Priority",
            description: "",
            version: "v2",
            style: "CLASSIC",
            services: null,
            products: null,
            images: [
                {
                    id: '1',
                    imageSrc: 'https://images.unsplash.com/photo-1614124760016-5fe39bdf27db?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2071&q=80',
                    imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
                },
            ],
            blogs: null,
            testimonials: null,
            portfolios: null,
            faqs: null,
            contactUs: null,
        },
    },

    {
        id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
        name: "Testimonials",
        version: "v1",
        style: "CLASSIC",
        path: "index",
        data: {
            type: "Testimonial",
            id: "k",
            title: "Testimonials",
            subTitle: "What Our Clients Say",
            description: "Read what our satisfied clients have to say about our logistics services.",
            version: "v1",
            style: "CLASSIC",
            services: null,
            products: null,
            images: null,
            blogs: null,
            portfolios: null,
            faqs: null,
            contactUs: null,
            termAndCondition: null,
            testimonials: [
                {
                    id: "1",
                    name: "John Doe",
                    designation: "Client",
                    imageSrc: "https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(2).jpg",
                    imageAlt: "John Doe",
                    testimonial:
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac magna sit amet risus tristique interdum, at vel velit in hac habitasse platea dictumst.",
                },
                {
                    id: "2",
                    name: "Jane Smith",
                    designation: "Business Owner",
                    imageSrc: "https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(1).jpg",
                    imageAlt: "Jane Smith",
                    testimonial:
                        "Praesent placerat enim ut ex tincidunt vehicula. Fusce sit amet dui tellus. Morbi sagittis, quam nec venenatis lobortis, mi risus tempus nulla, sed porttitor est nibh at nulla.",
                },
                {
                    id: "3",
                    name: "David Johnson",
                    designation: "CEO",
                    imageSrc: "https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(9).jpg",
                    imageAlt: "David Johnson",
                    testimonial:
                        "Ut posuere, ex a fringilla hendrerit, nulla metus gravida mi, in hendrerit quam odio sed est. Vestibulum nec finibus nisi. Aliquam et ipsum nulla.",
                },
                {
                    id: "4",
                    name: "Sarah Wilson",
                    designation: "Logistics Manager",
                    imageSrc: "https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(9).jpg",
                    imageAlt: "Sarah Wilson",
                    testimonial:
                        "Ut posuere, ex a fringilla hendrerit, nulla metus gravida mi, in hendrerit quam odio sed est. Vestibulum nec finibus nisi. Aliquam et ipsum nulla.",
                },
            ],
        },
    },
    {
        id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
        name: "Blog",
        version: "v1",
        style: "CLASSIC",
        path: "index",
        data: {
            type: "Blog",
            id: "k",
            title: "Explore Our Blog",
            subTitle: "Stay Informed and Inspired",
            description: "Discover insightful articles and stay updated with the latest trends and news in the logistics industry.",
            version: "v1",
            style: "CLASSIC",
            services: null,
            products: null,
            faqs: null,
            contactUs: null,
            portfolios: null,
            blogs: [
                {
                    id: "1",
                    title: "Tranquil Stays: Gayatri Lodge, Kasauli",
                    description: "Explore Tranquil Stays at Gayatri Lodge, a hidden gem nestled in the heart of Kasauli.",
                    descriptionContext: "Discover serenity and unmatched comfort at Gayatri Lodge, nestled in the heart of Kasauli.",
                    imageSrc: "https://images.unsplash.com/photo-1565793298595-6a879b1d9492?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2071&q=80",
                    imageAlt: 'Gayatri Lodge Kasauli',
                },
                {
                    id: "2",
                    title: "Luxury Unveiled: Gayatri Lodge Hotel",
                    description: "Experience Luxury Unveiled at Gayatri Lodge Hotel, where opulence meets elegance.",
                    descriptionContext: "Experience unparalleled luxury at Gayatri Lodge Hotel, where opulence meets elegance. Indulge in lavish accommodations, impeccable services, and breathtaking views.",
                    imageSrc: "https://images.unsplash.com/photo-1587293852726-70cdb56c2866?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2072&q=80",
                    imageAlt: 'Luxury Hotel',
                },
                {
                    id: "3",
                    title: "Heartfelt Welcome: Gayatri Lodge Homestay",
                    description: "Experience a Heartfelt Welcome at Gayatri Lodge Homestay, where personalized hospitality turns your stay into cherished memories.",
                    descriptionContext: "At Gayatri Lodge, we extend heartfelt welcomes and make you feel like family. Discover the warmth of personalized hospitality that turns your stay into cherished memories.",
                    imageSrc: "https://images.unsplash.com/photo-1606964212858-c215029db704?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80",
                    imageAlt: 'Homestay Welcome',
                },
                {
                    id: "4",
                    title: "Embrace Warmth: Personalized Hospitality at Gayatri Lodge",
                    description: "Embrace Warmth and Personalized Hospitality at Gayatri Lodge, where you're treated like family.",
                    descriptionContext: "At Gayatri Lodge, we extend heartfelt welcomes and make you feel like family. Discover the warmth of personalized hospitality that turns your stay into cherished memories.",
                    imageSrc: "https://images.unsplash.com/photo-1598193957011-39b9f2916992?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2069&q=80",
                    imageAlt: 'Warm Hospitality',
                },
            ],
            images: null,
            termAndCondition: null,
            testimonials: null,
        },
    },
    {
        id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
        name: "Contact Us",
        version: "v1",
        style: "CLASSIC",
        path: "index",
        data: {
            type: "ContactUs",
            id: "k",
            title: "Get In Touch",
            subTitle: "Let's Discuss Your Logistics Needs",
            description: "Reach out to us for inquiries and collaboration. Experience reliable logistics services that ensure your cargo reaches its destination safely and on time. Let's make your logistics journey hassle-free.",
            version: "v2",
            style: "CLASSIC",
            services: null,
            products: null,
            portfolios: null,
            blogs: null,
            images: null,
            faqs: null,
            contactUs: {
                address: "9 Nom Crescent Unit 2 \n Markham, Om L3S 2B3, CA",
                email: "info@drayworldlogistics.com",
                phone: "123-456-7890",
                formFields: [
                    { name: 'name', label: 'Name', type: 'text', required: true },
                    { name: 'email', label: 'Email', type: 'email', required: true },
                    { name: 'message', label: 'Message', type: 'textarea', required: true },
                ]
            },
            testimonials: null,
        },
    },
    {
        id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
        name: "Footer",
        version: "v2",
        style: "CLASSIC",
        path: "index",
        data: {
            type: "Footer",
            id: "k",
            title: "Hero Banner!",
            subTitle: "Hero Banner Sub Title is here",
            description: "Hero Banner Paragraph is here",
            version: "v2",
            style: "CLASSIC",
            services: null,
            products: null,
            portfolios: null,
            blogs: null,
            images: null,
            faqs: null,
            contactUs: null,
            testimonials: null,
            termAndCondition: null,
        },
    },
];

export const drayWorldLogisticSeo: any = {
    title: "Reliable Logistics Services | Dray World Logistics",
    description: "Dray World Logistics provides efficient and secure logistics services. We specialize in freight forwarding, warehousing, customs clearance, and last-mile delivery.",
    keywords: "Logistics, Freight Forwarding, Warehousing, Customs Clearance, Last-Mile Delivery, Cargo Transportation, Reliable Logistics",
    tags: "Logistics Services, Freight Forwarding, Warehousing Solutions, Customs Clearance, Last-Mile Delivery, Cargo Transportation, Reliable Logistics",
    author: "Your Name",
    imageUrl: "https://example.com/og-image.jpg",
    siteUrl: "https://www.drayworldlogistics.com",
};

export const drayWorldLogisticPlugin: PluginConfig[] = [
    {
        name: "FloatingButton",
        isActive: true,
        data: {
            "mobile": "123",
            "text": ""
        },
    }
]
