import { Section } from "../modal/Section";

export const northVibeDesignTheme: any = {
  name: "classic"
}

export const northVibeDesign: Section[] = [
  {
    id: "69e7ed7e-889d-41c0-a1d9-62bd150401e2",
    name: "Header",
    version: "v1",
    style: "MODERN",
    path: "index",
    data: {
      type: "Header",
      id: "001",
      title: "North Vibe Design",
      subTitle: "Hero Banner Sub Title is here",
      description: "To be the leading interior and exterior contracting company known for exceptional craftsmanship, creative designs, and customer satisfaction.",
      version: "v1",
      style: "MODERN",
      services: null,
      products: null,
      portfolios: null,
      images: null,
      blogs: null,
      testimonials: null,
      faqs: null,
      contactUs: {
        address: "Village",
        email: "northvibedesings@gmail.com",
        phone: "9805058367",
      },
    },
  },
  {
    id: "69e7ed7e-889d-41c0-a1d9-62bd150401e2",
    name: "Hero banner",
    version: "v1",
    style: "CLASSIC",
    path: "index",
    data: {
      type: "HeroBanner",
      id: "002",
      title: "North Vibe Design",
      subTitle: "Contact us today, and let us make your dream space a reality",
      description: "Contact us today, and let us make your dream space a reality",
      version: "v2",
      style: "CLASSIC",
      services: null,
      products: null,
      images: [
        {
          id: '1',
          imageSrc: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80',
          imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
        },
      ],
      blogs: null,
      testimonials: null,
      portfolios: null,
      faqs: null,
      contactUs: null,
    },
  },
  {
    id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
    name: "About-Us",
    version: "v1",
    style: "CLASSIC",
    path: "index",
    data: {
      type: "AboutUs",
      id: "003",
      title: "About North Vibe Design",
      subTitle: "Hero Banner Sub Title is here",
      description: "At North Vibe Design, we are dedicated to providing specialized expertise in ACP (Aluminium Composite Panel) installation, glass solutions, premium wooden flooring, and captivating ceiling designs. Our services cater to storefronts, outdoor patios, pools, gardens, office buildings, apartments, hotels, shops, supermarkets, and more. ",
      version: "v1",
      style: "CLASSIC",
      services: null,
      products: null,
      images: [
        {
          id: '1',
          imageSrc: 'https://images.unsplash.com/photo-1600585154363-67eb9e2e2099?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDE1fHx8ZW58MHx8fHx8&auto=format&fit=crop&w=500&q=60',
          imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
        },
      ],
      blogs: null,
      testimonials: null,
      portfolios: null,
      faqs: null,
      contactUs: null,
    },
  },

  {
    id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
    name: "Service",
    version: "v1",
    style: "CLASSIC",
    path: "index",
    data: {
      type: "Portfolio",
      id: "k",
      title: "Our Recent Work",
      subTitle: "Hero Banner Sub Title is here",
      description: "Hero Banner Paragraph is here",
      version: "v1",
      style: "CLASSIC",
      blogs: null,
      faqs: null,
      contactUs: null,
      portfolios: [
        {
          id: 1,
          name: 'Hotel Building. 4000/sqt',
          description: 'Our hotel building designs focus on guest comfort and satisfaction.',
          imageSrc: 'https://images.unsplash.com/photo-1617836330596-d8c050a4cfd9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1207&q=80',
          imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
          href: '#',
        },
        {
          id: 2,
          name: 'Shop Building',
          description: ' Tailored retail space designs for various shop types.',
          imageSrc: 'https://images.unsplash.com/photo-1617836330596-d8c050a4cfd9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1207&q=80',
          imageAlt: 'Wood table with porcelain mug, leather journal, brass pen, leather key ring, and a houseplant.',
          href: '#',
        },
        {
          id: 3,
          name: 'Clothing Store',
          description: 'Journals and note-taking',
          imageSrc: 'https://images.unsplash.com/photo-1617836330596-d8c050a4cfd9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1207&q=80',
          imageAlt: 'Wood table with porcelain mug, leather journal, brass pen, leather key ring, and a houseplant.',
          href: '#',
        },
        {
          id: 4,
          name: 'Self-Improvement',
          description: 'Journals and note-taking',
          imageSrc: 'https://tailwindui.com/img/ecommerce-images/home-page-02-edition-02.jpg',
          imageAlt: 'Wood table with porcelain mug, leather journal, brass pen, leather key ring, and a houseplant.',
          href: '#',
        },
        {
          id: 5,
          name: 'Travel',
          description: 'Daily commute essentials',
          imageSrc: 'https://tailwindui.com/img/ecommerce-images/home-page-02-edition-03.jpg',
          imageAlt: 'Collection of four insulated travel bottles on wooden shelf.',
          href: '#',
        },
      ],
      services: null,
      products: null,
      images: null,
      testimonials: null,
    },
  },
  {
    id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
    name: "Gallery",
    version: "v1",
    style: "MODERN",
    path: "index",
    data: {
      type: "Gallery",
      id: "004",
      title: "Our Gallery!",
      subTitle: "Hero Banner Sub Title is here",
      description: "Hero Banner Paragraph is here",
      version: "v1",
      style: "MODERN",
      services: null,
      products: null,
      portfolios: null,
      faqs: null,
      images: [
        {
          id: '1',
          imageSrc: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDd8fHxlbnwwfHx8fHw%3D&auto=format&fit=crop&w=500&q=60',
          imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
        },
        {
          id: '2',
          imageSrc: 'https://images.unsplash.com/photo-1604014238170-4def1e4e6fcf?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDZ8fHxlbnwwfHx8fHw%3D&auto=format&fit=crop&w=500&q=60',
          imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
        },
        {
          id: '3',
          imageSrc: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDEwfHx8ZW58MHx8fHx8&auto=format&fit=crop&w=500&q=60',
          imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
        },
        {
          id: '4',
          imageSrc: 'https://images.unsplash.com/photo-1513584684374-8bab748fbf90?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDE0fHx8ZW58MHx8fHx8&auto=format&fit=crop&w=500&q=60',
          imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
        },
        {
          id: '6',
          imageSrc: 'https://images.unsplash.com/photo-1531971589569-0d9370cbe1e5?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDV8fHxlbnwwfHx8fHw%3D&auto=format&fit=crop&w=500&q=60',
          imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
        }, {
          id: '7',
          imageSrc: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1171&q=80',
          imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
        }, {
          id: '8',
          imageSrc: 'https://images.unsplash.com/photo-1508167290553-87a67eca5bf5?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTZ8fHJvb2Z8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=500&q=60',
          imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
        }, {
          id: '9',
          imageSrc: 'https://images.unsplash.com/photo-1574598762239-6b6f96eab341?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1074&q=80',
          imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
        },
      ],
      blogs: null,
      testimonials: null,
      contactUs: null,
    },
  },
  {
    id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
    name: "Service",
    version: "v1",
    style: "CLASSIC",
    path: "index",
    data: {
      type: "Service",
      id: "k",
      title: "Our Services",
      subTitle: "Hero Banner Sub Title is here",
      description: "We are provided following services to our customers",
      version: "v2",
      style: "CLASSIC",
      blogs: null,
      faqs: null,
      contactUs: null,
      portfolios: null,
      services: [
        {
          id: 1,
          title: 'ACP Installation',
          body: 'Transform interiors and exteriors with durable and stylish Aluminum Composite Panels, adding a contemporary flair to buildings.',
          imageSrc: 'https://htmldemo.zcubethemes.com/riorelax/img/icon/sve-icon3.png',
          imageAlt: 'parking icon',
        },
        {
          id: 2,
          title: 'Wooden Flooring',
          body: 'Add warmth and elegance with our premium wooden flooring options, tailored to your style and space.',
          imageSrc: 'https://htmldemo.zcubethemes.com/riorelax/img/icon/fe-icon01.png',
          imageAlt: 'parking icon',
        },
        {
          id: 3,
          title: 'Glass Solutions',
          body: 'Enhance natural light and aesthetics with professional glass installations for windows, doors, partitions, and facades.',
          imageSrc: 'https://htmldemo.zcubethemes.com/riorelax/img/icon/sve-icon2.png',
          imageAlt: 'parking icon',
        },
        {
          id: 4,
          title: 'Wooden Flooring',
          body: 'Add warmth and elegance with our premium wooden flooring options, tailored to your style and space.',
          imageSrc: 'https://htmldemo.zcubethemes.com/riorelax/img/icon/fe-icon08.png',
          imageAlt: 'parking icon',
        },
        {
          id: 5,
          title: 'Ceiling Designing',
          body: 'Turn plain ceilings into captivating focal points with unique and visually striking designs.',
          imageSrc: 'https://htmldemo.zcubethemes.com/riorelax/img/icon/fe-icon05.png',
          imageAlt: 'parking icon',
        },
        {
          id: 6,
          title: 'Roof Solutions',
          body: 'Comprehensive roofing services, from installation to maintenance, ensuring durability and weather resistance.',
          imageSrc: 'https://htmldemo.zcubethemes.com/riorelax/img/icon/fe-icon05.png',
          imageAlt: 'parking icon',
        },
      ],
      products: null,
      images: null,
      testimonials: null,
    },
  },
  {
    id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
    name: "Blog",
    version: "v1",
    style: "CLASSIC",
    path: "index",
    data: {
      type: "Blog",
      id: "k",
      title: "Our Blogs!",
      subTitle: "Hero Banner Sub Title is here",
      description: "Hero Banner Paragraph is here",
      version: "v1",
      style: "CLASSIC",
      services: null,
      products: null,
      faqs: null,
      contactUs: null,
      portfolios: null,
      blogs: [
        {
          id: "1",
          title: "Storefront Window Display: Captivating Passersby",
          description: "Discover creative ideas to design compelling storefront window displays that attract and engage potential customers.",
          descriptionContext: "Enhance your retail space with eye-catching window displays that tell your brand's story and entice visitors to step inside.",
          imageSrc: "https://images.unsplash.com/photo-1617836330596-d8c050a4cfd9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1207&q=80",
          imageAlt: "Tall slender porcelain bottle with natural clay textured body and cork stopper.",
        },
        {
          id: "2",
          title: "Outdoor Patio Perfection: Designs for Entertaining Guests",
          description: "Create an inviting outdoor entertainment space with various patio designs that set the stage for unforgettable gatherings.",
          descriptionContext: "Elevate your patio into a hub for entertainment and relaxation, where friends and family can connect amidst stylish and comfortable surroundings.",
          imageSrc: "https://images.unsplash.com/photo-1516484411845-e74b77f26b83?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1172&q=80",
          imageAlt: "Tall slender porcelain bottle with natural clay textured body and cork stopper.",
        },
        {
          id: "3",
          title: "Office Productivity Boost: Enhance Your Workspace Design",
          description: "Unlock productivity potential by optimizing your workspace layout, lighting, and ergonomic design.",
          descriptionContext: "A well-designed office environment can boost employee morale, creativity, and overall efficiency.",
          imageSrc: "https://images.unsplash.com/photo-1542581509-7e87190743b6?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
          imageAlt: "Modern office interior with ergonomic furniture and natural lighting.",
        },
        {
          id: "4",
          title: "Restaurant Interior Ideas: A Recipe for Success",
          description: "Explore innovative restaurant interior designs that enhance the dining experience and leave a lasting impression on patrons.",
          descriptionContext: "From cozy cafes to upscale dining, interior design plays a crucial role in creating a memorable atmosphere.",
          imageSrc: "https://images.unsplash.com/photo-1505275350441-83dcda8eeef5?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1074&q=80",
          imageAlt: "Stylish restaurant interior with modern furnishings and artistic decor.",
        },
        {
          id: "5",
          title: "Hotel Bathroom Luxe: Five-Star Amenities You Can Have",
          description: "Elevate your bathroom design to hotel-level luxury with high-end fixtures, materials, and spa-like features.",
          descriptionContext: "Transform your bathroom into a serene oasis where relaxation and indulgence go hand in hand.",
          imageSrc: "https://plus.unsplash.com/premium_photo-1661412671807-7c1f94169607?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1264&q=80",
          imageAlt: "Elegant hotel bathroom with luxurious bathtub and marble finishes.",
        },
        {
          id: "6",
          title: "Exhibition Space Planning: Captivate Visitors with Innovative Design",
          description: "Designing exhibition spaces that engage and captivate visitors through strategic layout, interactive elements, and immersive experiences.",
          descriptionContext: "Explore the art of creating impactful exhibitions that leave a lasting impression on attendees.",
          imageSrc: "https://images.unsplash.com/photo-1501127122-f385ca6ddd9d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=435&q=80",
          imageAlt: "Art gallery with innovative exhibition design and interactive installations.",
        },
        {
          id: "7",
          title: "The Rise of Coworking Spaces: The Future of Work",
          description: "Explore the evolving trend of coworking spaces, their benefits for freelancers and businesses, and the future of flexible work environments.",
          descriptionContext: "Discover how shared workspaces are redefining the traditional office and shaping the way people collaborate.",
          imageSrc: "https://images.unsplash.com/photo-1527192491265-7e15c55b1ed2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
          imageAlt: "Coworking space with modern decor and collaborative work areas.",
        },
        {
          id: "8",
          title: "Retail Store Makeover: Transform Your Space for Success",
          description: "Revitalize your retail store with strategic redesigns, visual merchandising, and customer-centric layouts that drive sales and brand loyalty.",
          descriptionContext: "Discover how a refreshed store environment can attract customers, enhance their shopping experience, and increase revenue.",
          imageSrc: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
          imageAlt: "Modern retail store interior with attractive displays and welcoming ambiance.",
        },
      ],
      images: null,
      testimonials: null,
    },
  },
  {
    id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
    name: "Footer",
    version: "v1",
    style: "CLASSIC",
    path: "index",
    data: {
      type: "ContactUs",
      id: "k",
      title: "Get In Touch",
      subTitle: "Hero Banner Sub Title is here",
      description: "Hero Banner Paragraph is here",
      version: "v2",
      style: "CLASSIC",
      services: null,
      products: null,
      portfolios: null,
      blogs: null,
      images: null,
      faqs: null,
      contactUs: {
        address: "Village",
        email: "northvibedesings@gmail.com",
        phone: "9805058367",
      },
      testimonials: null,
    },
  },
  {
    id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
    name: "Footer",
    version: "v1",
    style: "CLASSIC",
    path: "index",
    data: {
      type: "Footer",
      id: "k",
      title: "Hero Banner!",
      subTitle: "Hero Banner Sub Title is here",
      description: "Hero Banner Paragraph is here",
      version: "v1",
      style: "CLASSIC",
      services: null,
      products: null,
      blogs: null,
      portfolios: null,
      images: null,
      faqs: null,
      contactUs: null,
      testimonials: null,
    },
  },
];

export const northVibeDesignSeo: any = {
  title: "Top Interior and Exterior Design Services in North India | North Vibe Design",
  description: "Elevate your spaces with exceptional craftsmanship and creative designs. We specialize in ACP installation, glass solutions, wooden flooring, and ceiling designs. Catering to residential and commercial clients in Himachal Pradesh and North India.",
  keywords: "Interior design, exterior design, ACP installation, glass solutions, wooden flooring, ceiling designs, residential services, commercial services, remodeling, real estate, architecture, hospitality, landscape architects, Himachal Pradesh, North India.",
  tags: "Interior Design, Exterior Design, ACP Installation, Glass Solutions, Wooden Flooring, Ceiling Designs, Residential Services, Commercial Services, Remodeling, Real Estate, Architecture, Hospitality, Landscape Architects, Himachal Pradesh, North India.",
  author: "Pankaj Kumar",
  imageUrl: "https://example.com/og-image.jpg",
  siteUrl: "https://www.pahariyatri.com",
};
