import { Section } from "../modal/Section";
import { SeoData } from "../modal/SeoData";

export const techiepahariyatriseo: SeoData = {
    title: "Pankaj Kumar - Experienced Software Engineer Portfolio",
    description: "Explore the portfolio of Pankaj Kumar, an experienced Software Engineer specializing in full-stack development, front-end and back-end techniques, and delivering high-quality software solutions.",
    keywords: "Pankaj Kumar, software engineer, portfolio, full-stack development, front-end, back-end, AWS, Java, React, Flutter, DevOps",
    tags: "Pankaj Kumar, software engineer, portfolio, full-stack development, front-end, back-end, AWS, Java, React, Flutter, DevOps",
    author: "Pankaj Kumar",
    imageUrl: "https://example.com/portfolio-og-image.jpg",
    siteUrl: "https://techie.pahariyatri.com",
};

export const techieTheme: any = {
    name: "classic"
}

export const techie: Section[] = [
    {
        id: "69e7ed7e-889d-41c0-a1d9-62bd150401e2",
        name: "Header",
        version: "v2", // Add version property
        style: "CLASSIC", // Add style property
        path: "index",
        data: {
            type: "Header",
            id: "001",
            title: "Portfolio",
            subTitle: "Hero Banner Sub Title is",
            description: "Hero Banner Paragraph is here",
            version: "v1",
            style: "CLASSIC",
            services: null,
            products: null,
            portfolios: null,
            images: null,
            blogs: null,
            testimonials: null,
            faqs: null,
            contactUs: null,
        },
    },
    {
        id: "69e7ed7e-889d-41c0-a1d9-62bd150401e2",
        name: "Herobanner",
        version: "v1", // Add version property
        style: "CLASSIC", // Add style property
        path: "index",
        data: {
            type: "HeroBanner",
            id: "002",
            title: "Pankaj Kumar",
            subTitle: "Software engineer know they don’t know everything, but also know they can learn anything",
            description: "Hero Banner Paragraph is here",
            version: "v2",
            style: "CLASSIC",
            services: null,
            products: null,
            images: [
                {
                    id: '1',
                    imageSrc: 'https://images.unsplash.com/photo-1571171637578-41bc2dd41cd2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80',
                    imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
                },
            ],
            blogs: null,
            testimonials: null,
            portfolios: null,
            faqs: null,
            contactUs: null,
        },
    },
    {
        id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
        name: "Service",
        version: "v1",
        style: "MODERN",
        path: "index",
        data: {
            type: "AboutUs",
            id: "003",
            title: "About me!",
            subTitle: "Hero Banner Sub Title is here",
            description: "Experienced Software Engineer specializing in backend development with expertise in Java andbuilding robust applications using Spring Boot. Proficient in integrating frontend technologies likeJavaScript and TypeScript. Skilled in containerization with Docker and deployment using CI/CDpipelines like Jenkins. Familiar with Flutter for cross-platform mobile app development",
            version: "v1",
            style: "MODERN",
            services: null,
            products: null,
            images: [
                {
                    "id": "1",
                    "imageAlt": 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
                    "imageSrc": "https://pbs.twimg.com/profile_images/1267037032867598338/WuIcKTuF_400x400.jpg"
                }
            ],
            blogs: null,
            testimonials: null,
            portfolios: null,
            faqs: null,
            contactUs: null,
        },
    },
    {
        id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
        name: "Footer",
        version: "v2",
        style: "CLASSIC",
        path: "index",
        data: {
            type: "Timeline",
            id: "k",
            title: "Hero Banner!",
            subTitle: "Hero Banner Sub Title is here",
            description: "Hero Banner Paragraph is here",
            version: "v2",
            style: "CLASSIC",
            services: null,
            products: null,
            portfolios: null,
            blogs: null,
            images: null,
            faqs: null,
            contactUs: null,
            testimonials: null,
        },
    },
    {
        id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
        name: "Service",
        version: "v1",
        style: "CLASSIC",
        path: "index",
        data: {
            type: "Portfolio",
            id: "k",
            title: "Our Portfolio",
            subTitle: "Hero Banner Sub Title is here",
            description: "Hero Banner Paragraph is here",
            version: "v1",
            style: "CLASSIC",
            blogs: null,
            faqs: null,
            contactUs: null,
            portfolios: [
                {
                    id: 1,
                    name: 'Desk and Office',
                    description: 'Work from home accessories',
                    imageSrc: 'https://tailwindui.com/img/ecommerce-images/home-page-02-edition-01.jpg',
                    imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
                    href: '#',
                },
                {
                    id: 2,
                    name: 'Self-Improvement',
                    description: 'Journals and note-taking',
                    imageSrc: 'https://tailwindui.com/img/ecommerce-images/home-page-02-edition-02.jpg',
                    imageAlt: 'Wood table with porcelain mug, leather journal, brass pen, leather key ring, and a houseplant.',
                    href: '#',
                },
                {
                    id: 3,
                    name: 'Self-Improvement',
                    description: 'Journals and note-taking',
                    imageSrc: 'https://tailwindui.com/img/ecommerce-images/home-page-02-edition-02.jpg',
                    imageAlt: 'Wood table with porcelain mug, leather journal, brass pen, leather key ring, and a houseplant.',
                    href: '#',
                },
                {
                    id: 4,
                    name: 'Self-Improvement',
                    description: 'Journals and note-taking',
                    imageSrc: 'https://tailwindui.com/img/ecommerce-images/home-page-02-edition-02.jpg',
                    imageAlt: 'Wood table with porcelain mug, leather journal, brass pen, leather key ring, and a houseplant.',
                    href: '#',
                },
                {
                    id: 5,
                    name: 'Travel',
                    description: 'Daily commute essentials',
                    imageSrc: 'https://tailwindui.com/img/ecommerce-images/home-page-02-edition-03.jpg',
                    imageAlt: 'Collection of four insulated travel bottles on wooden shelf.',
                    href: '#',
                },
            ],
            services: [
                {
                    id: 1,
                    title: 'Interior Design:',
                    body: 'Create captivating and functional interiors for corporate offices, hotels, and retail spaces that reflect your brand identity.',
                    imageSrc: 'https://htmldemo.zcubethemes.com/riorelax/img/icon/sve-icon3.png',
                    imageAlt: 'parking icon',
                },
                {
                    id: 2,
                    title: 'Exterior Design',
                    body: ' Craft striking facades and landscape concepts for commercial buildings, hotels, and shops to leave a lasting impression.',
                    imageSrc: 'https://htmldemo.zcubethemes.com/riorelax/img/icon/fe-icon01.png',
                    imageAlt: 'parking icon',
                },
                {
                    id: 3,
                    title: 'ACP and Aluminum Design',
                    body: 'Harness the versatility of ACP and aluminum to bring modern and elegant architectural visions to life.',
                    imageSrc: 'https://htmldemo.zcubethemes.com/riorelax/img/icon/sve-icon2.png',
                    imageAlt: 'parking icon',
                },
                {
                    id: 4,
                    title: 'Glass Solutions',
                    body: 'Experience the elegance of glass with custom-designed facades, partitions, and skylights for seamless interior-exterior connections.',
                    imageSrc: 'https://htmldemo.zcubethemes.com/riorelax/img/icon/fe-icon08.png',
                    imageAlt: 'parking icon',
                },
                {
                    id: 5,
                    title: 'Wooden Flooring',
                    body: 'Add warmth and sophistication to your spaces with hardwood, engineered wood, and laminate flooring options.',
                    imageSrc: 'https://htmldemo.zcubethemes.com/riorelax/img/icon/fe-icon05.png',
                    imageAlt: 'parking icon',
                },
                {
                    id: 6,
                    title: 'Ceiling Design',
                    body: 'Elevate your interiors with innovative and artistic ceiling designs that enhance the ambiance and aesthetics of any space.',
                    imageSrc: 'https://htmldemo.zcubethemes.com/riorelax/img/icon/fe-icon05.png',
                    imageAlt: 'parking icon',
                },
            ],
            products: null,
            images: null,
            testimonials: null,
        },
    },
    {
        id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
        name: "Service",
        version: "v1",
        style: "CLASSIC",
        path: "index",
        data: {
            type: "OurTeam",
            id: "k",
            title: "Meet our leadership",
            subTitle: "Hero Banner Sub Title is here",
            description: "Libero fames augue nisl porttitor nisi, quis. Id ac elit odio vitae elementum enim vitae ullamcorper suspendisse.",
            version: "v1",
            style: "CLASSIC",
            blogs: null,
            faqs: null,
            contactUs: null,
            portfolios: null,
            services: null,
            ourTeam: [
                {
                    id: 1,
                    name: 'Leslie Alexander',
                    role: 'Co-Founder / CEO',
                    description: 'Work from home accessories',
                    imageSrc: 'https://tailwindui.com/img/ecommerce-images/home-page-02-edition-01.jpg',
                    imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
                    href: '#',
                },
                {
                    id: 2,
                    name: 'Alex',
                    role: 'Co-Founder / CEO',
                    description: 'Journals and note-taking',
                    imageSrc: 'https://tailwindui.com/img/ecommerce-images/home-page-02-edition-02.jpg',
                    imageAlt: 'Wood table with porcelain mug, leather journal, brass pen, leather key ring, and a houseplant.',
                    href: '#',
                },
                {
                    id: 3,
                    name: 'Self-Improvement',
                    role: 'Co-Founder / CEO',
                    description: 'Journals and note-taking',
                    imageSrc: 'https://tailwindui.com/img/ecommerce-images/home-page-02-edition-02.jpg',
                    imageAlt: 'Wood table with porcelain mug, leather journal, brass pen, leather key ring, and a houseplant.',
                    href: '#',
                },
                {
                    id: 4,
                    name: 'Self-Improvement',
                    role: 'HR',
                    description: 'Journals and note-taking',
                    imageSrc: 'https://tailwindui.com/img/ecommerce-images/home-page-02-edition-02.jpg',
                    imageAlt: 'Wood table with porcelain mug, leather journal, brass pen, leather key ring, and a houseplant.',
                    href: '#',
                },
                {
                    id: 5,
                    name: 'Travel',
                    role: 'BA',
                    description: 'Daily commute essentials',
                    imageSrc: 'https://tailwindui.com/img/ecommerce-images/home-page-02-edition-03.jpg',
                    imageAlt: 'Collection of four insulated travel bottles on wooden shelf.',
                    href: '#',
                },
            ],
            products: null,
            images: null,
            testimonials: null,
        },
    },
    {
        id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
        name: "ContactUs",
        version: "v1",
        style: "CLASSIC",
        path: "index",
        data: {
            type: "ContactUs",
            id: "k",
            title: "Get in Touch",
            subTitle: "",
            description: "Hero Banner Paragraph is here",
            version: "v1",
            style: "CLASSIC",
            services: null,
            products: null,
            images: null,
            testimonials: null,
            portfolios: null,
            faqs: null,
            blogs: null,
            contactUs: {
                address: "Village Khurahal, Tehsil Sundar Nagar, Himachal Pradesh 174403",
                email: "pankajkumar.techie@gmail.com",
                phone: "9569576707",
            },
        },
    },
    {
        id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
        name: "Footer",
        version: "v1",
        style: "CLASSIC",
        path: "index",
        data: {
            type: "Footer",
            id: "k",
            title: "Hero Banner!",
            subTitle: "Hero Banner Sub Title is here",
            description: "Hero Banner Paragraph is here",
            version: "v1",
            style: "CLASSIC",
            services: null,
            products: null,
            portfolios: null,
            blogs: null,
            images: null,
            faqs: null,
            contactUs: null,
            testimonials: null,
        },
    },
];