import { Section } from "../modal/Section";

export const websites: Section[] = [
    {
        id: "69e7ed7e-889d-41c0-a1d9-62bd150401e2",
        name: "Header",
        version: "v1", // Add version property
        style: "CLASSIC", // Add style property
        path: "index",
        data: {
          type: "Header",
          id: "001",
          title: "Hero Banner!",
          subTitle: "Hero Banner Sub Title is here",
          description: "Hero Banner Paragraph is here",
          version: "v1",
          style: "CLASSIC",
          services: null,
          products: null,
          images: null,
          blogs : null,
          testimonials: null,
          bgColor: null,
        },
      },
  {
    id: "69e7ed7e-889d-41c0-a1d9-62bd150401e2",
    name: "Herobanner",
    version: "v1", // Add version property
    style: "CLASSIC", // Add style property
    path: "index",
    data: {
      type: "HeroBanner",
      id: "002",
      title: "Hero Banner!",
      subTitle: "Hero Banner Sub Title is here",
      description: "Hero Banner Paragraph is here",
      version: "v1",
      style: "CLASSIC",
      services: null,
      products: null,
      images: null,
      blogs : null,
      testimonials: null,
      bgColor: null,
    },
  },
  {
    id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
    name: "Service",
    version: "v1",
    style: "CLASSIC",
    path: "index",
    data: {
      type: "AboutUs",
      id: "003",
      title: "About us!",
      subTitle: "Hero Banner Sub Title is here",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
      version: "v1",
      style: "CLASSIC",
      services: null,
      products: null,
      images: null,
      blogs : null,
      testimonials: null,
      bgColor: null,
    },
  },
  {
    id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
    name: "Gallery",
    version: "v1",
    style: "CLASSIC",
    path: "index",
    data: {
      type: "Gallery",
      id: "004",
      title: "Gallery !",
      subTitle: "Hero Banner Sub Title is here",
      description: "Hero Banner Paragraph is here",
      version: "v1",
      style: "CLASSIC",
      services: null,
      products: null,
      images: [
        {
            id: '1',
            imageSrc: 'https://tailwindui.com/img/ecommerce-images/home-page-02-edition-01.jpg',
            imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
        },
        {
            id: '2',
            imageSrc: 'https://images.unsplash.com/photo-1684752097893-13785863f9a1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=435&q=80',
            imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
        },
        {
            id: '3',
            imageSrc: 'https://images.unsplash.com/photo-1682695797221-8164ff1fafc9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80',
            imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
        },
        {
            id: '4',
            imageSrc: 'https://images.unsplash.com/photo-1682695797221-8164ff1fafc9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80',
            imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
        },
    ],
    blogs : null,
    testimonials: null,
      bgColor: null,
    },
  },
  {
    id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
    name: " ",
    version: "v1",
    style: "CLASSIC",
    path: "index",
    data: {
      type: "Product",
      id: "k",
      title: "Our Rooms!",
      subTitle: "Hero Banner Sub Title is here",
      description: "Hero Banner Paragraph is here",
      version: "v1",
      style: "CLASSIC",
      services: null,
      blogs : null,
      products: [
        {
            id: 1,
            name: 'Deluxe Room',
            href: '#',
            description: 'Spacious, elegant, and luxurious accommodation for ultimate comfort.',
            imageSrc: 'http://wahabali.com/work/pearl-demo/imgs/room-img1.jpg',
            imageAlt: 'Tall slender porcelain bottle with natural clay textured body and cork stopper.',
        },
        {
            id: 2,
            name: 'Master Room',
            href: '#',
            description: 'Opulent, indulgent, and exclusive retreat for discerning guests.',
            imageSrc: 'http://wahabali.com/work/pearl-demo/imgs/room-img4.jpg',
            imageAlt: 'Olive drab green insulated bottle with flared screw lid and flat top.',
        },
        {
            id: 3,
            name: 'Super Room',
            href: '#',
            description: ' Upgraded, luxurious, and lavish accommodation for a remarkable stay.',
            imageSrc: 'http://wahabali.com/work/pearl-demo/imgs/room-img3.jpg',
            imageAlt: 'Person using a pen to cross a task off a productivity paper card.',
        },
        {
            id: 4,
            name: 'Normal Room',
            href: '#',
            description: 'Comfortable, affordable, and practical choice for a pleasant stay.',
            imageSrc: 'http://wahabali.com/work/pearl-demo/imgs/room-img2.jpg',
            imageAlt: 'Hand holding black machined steel mechanical pencil with brass tip and top.',
        },
        // More products...
    ],
      images: null,
      testimonials: null,
      bgColor: null,
    },
  },
  {
    id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
    name: "Service",
    version: "v1",
    style: "CLASSIC",
    path: "index",
    data: {
      type: "Service",
      id: "k",
      title: "Our Services",
      subTitle: "Hero Banner Sub Title is here",
      description: "Hero Banner Paragraph is here",
      version: "v1",
      style: "CLASSIC",
      blogs : null,
      services: [
        {
            id: 1,
            title: 'Parking Space',
            body: 'We dejoy working with discerning clients, people for whom qualuty, service, integrity & aesthetics.',
            imageSrc: 'https://htmldemo.zcubethemes.com/riorelax/img/icon/sve-icon3.png',
            imageAlt: 'parking icon',
        },
        {
            id: 2,
            title: 'Room Service',
            body: 'We dejoy working with discerning clients, people for whom qualuty, service, integrity & aesthetics.',
            imageSrc: 'https://htmldemo.zcubethemes.com/riorelax/img/icon/fe-icon01.png',
            imageAlt: 'parking icon',
        },
        {
            id: 3,
            title: 'Fibre Internet',
            body: 'We dejoy working with discerning clients, people for whom qualuty, service, integrity & aesthetics.',
            imageSrc: 'https://htmldemo.zcubethemes.com/riorelax/img/icon/sve-icon2.png',
            imageAlt: 'parking icon',
        },
        {
            id: 4,
            title: 'Special Offers',
            body: 'We dejoy working with discerning clients, people for whom qualuty, service, integrity & aesthetics.',
            imageSrc: 'https://htmldemo.zcubethemes.com/riorelax/img/icon/fe-icon08.png',
            imageAlt: 'parking icon',
        },
        {
            id: 5,
            title: 'Best Accommodation',
            body: 'We dejoy working with discerning clients, people for whom qualuty, service, integrity & aesthetics.',
            imageSrc: 'https://htmldemo.zcubethemes.com/riorelax/img/icon/fe-icon05.png',
            imageAlt: 'parking icon',
        },
        {
            id: 6,
            title: 'Breakfast',
            body: 'We dejoy working with discerning clients, people for whom qualuty, service, integrity & aesthetics.',
            imageSrc: 'https://htmldemo.zcubethemes.com/riorelax/img/icon/fe-icon05.png',
            imageAlt: 'parking icon',
        },
      ],
      products: null,
      images: null,
      testimonials: null,
      bgColor: null,
    },
  },
  {
    id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
    name: "Service",
    version: "v1",
    style: "CLASSIC",
    path: "index",
    data: {
      type: "Blog",
      id: "k",
      title: "Hero Banner!",
      subTitle: "Hero Banner Sub Title is here",
      description: "Hero Banner Paragraph is here",
      version: "v1",
      style: "CLASSIC",
      services: null,
      products: null,
      blogs : [
        {
          id: "1",
          title: "Blog Post 1",
          description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
          descriptionContext: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nonummy tincidunt ut lacreet dolore magna aliguam erat volutpat.",
          imageSrc: 'http://wahabali.com/work/pearl-demo/imgs/room-img1.jpg',
          imageAlt: 'Tall slender porcelain bottle with natural clay textured body and cork stopper.',
        },
        {
          id: "2",
          title: "Blog Post 2",
          description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
          descriptionContext: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nonummy tincidunt ut lacreet dolore magna aliguam erat volutpat.",
          imageSrc: 'http://wahabali.com/work/pearl-demo/imgs/room-img1.jpg',
          imageAlt: 'Tall slender porcelain bottle with natural clay textured body and cork stopper.',
        },
        {
          id: "3",
          title: "Blog Post 3",
          description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
          descriptionContext: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nonummy tincidunt ut lacreet dolore magna aliguam erat volutpat.",
          imageSrc: 'http://wahabali.com/work/pearl-demo/imgs/room-img1.jpg',
          imageAlt: 'Tall slender porcelain bottle with natural clay textured body and cork stopper.',
        },
        {
          id: "4",
          title: "Blog Post 3",
          description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
          descriptionContext: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nonummy tincidunt ut lacreet dolore magna aliguam erat volutpat.",
          imageSrc: 'http://wahabali.com/work/pearl-demo/imgs/room-img1.jpg',
          imageAlt: 'Tall slender porcelain bottle with natural clay textured body and cork stopper.',
        },
      ],
      images: null,
      testimonials: null,
      bgColor: null,
    },
  },
  {
    id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
    name: "Service",
    version: "v1",
    style: "CLASSIC",
    path: "index",
    data: {
      type: "Testimonial",
      id: "k",
      title: "Hero Banner!",
      subTitle: "Hero Banner Sub Title is here",
      description: "Hero Banner Paragraph is here",
      version: "v1",
      style: "CLASSIC",
      services: null,
      products: null,
      images: null,
      blogs : null,
      testimonials: [
        {
          id: "1",
          name: "John Doe",
          designation: "Graphic Designer",
          imageSrc: "https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(2).jpg",
          imageAlt: "Graphic Designer",
          testimonial:
              "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac magna sit amet risus tristique interdum, at vel velit in hac habitasse platea dictumst.",
      },
      {
          id: "2",
          name: "John Doe",
          designation: "John Doe",
          imageSrc: "https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(1).jpg",
          imageAlt: "John Doe",
          testimonial:
              "Praesent placerat enim ut ex tincidunt vehicula. Fusce sit amet dui tellus. Morbi sagittis, quam nec venenatis lobortis, mi risus tempus nulla, sed porttitor est nibh at nulla.",
      },
      {
          id: "3",
          name: "John Doe",
          designation: "John Doe",
          imageSrc: "https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(9).jpg",
          imageAlt: "John Doe",
          testimonial:
              "Ut posuere, ex a fringilla hendrerit, nulla metus gravida mi, in hendrerit quam odio sed est. Vestibulum nec finibus nisi. Aliquam et ipsum nulla.",
      },
      ],
      bgColor: null,
    },
  },
  {
    id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
    name: "Service",
    version: "v1",
    style: "CLASSIC",
    path: "index",
    data: {
      type: "ContactUs",
      id: "k",
      title: "Hero Banner!",
      subTitle: "Hero Banner Sub Title is here",
      description: "Hero Banner Paragraph is here",
      version: "v1",
      style: "CLASSIC",
      services: null,
      products: null,
      images: null,
      testimonials: null,
      blogs : null,
      bgColor: null,
    },
  },
  {
    id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
    name: "Faq",
    version: "v1",
    style: "CLASSIC",
    path: "index",
    data: {
      type: "FAQ",
      id: "k",
      title: "Hero Banner!",
      subTitle: "Hero Banner Sub Title is here",
      description: "Hero Banner Paragraph is here",
      version: "v1",
      style: "CLASSIC",
      services: null,
      products: null,
      images: null,
      blogs : null,
      testimonials: null,
      bgColor: null,
    },
  },
  {
    id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
    name: "Footer",
    version: "v1",
    style: "CLASSIC",
    path: "index",
    data: {
      type: "Footer",
      id: "k",
      title: "Hero Banner!",
      subTitle: "Hero Banner Sub Title is here",
      description: "Hero Banner Paragraph is here",
      version: "v1",
      style: "CLASSIC",
      services: null,
      products: null,
      blogs : null,
      images: null,
      testimonials: null,
      bgColor: null,
    },
  },
];
