import { Section } from "../modal/Section";

export const websites: Section[] = [
    {
        id: "69e7ed7e-889d-41c0-a1d9-62bd150401e2",
        name: "Home Page",
        version: "v1", // Add version property
        style: "CLASSIC", // Add style property
        path: "index",
        htmlId: null,
        data: {
          type: "Header",
          id: "k",
          title: "Hero Banner!",
          subTitle: "Hero Banner Sub Title is here",
          description: "Hero Banner Paragraph is here",
          version: "v1",
          style: "CLASSIC",
          services: null,
          imageDtos: null,
          bgColor: null,
        },
      },
  {
    id: "69e7ed7e-889d-41c0-a1d9-62bd150401e2",
    name: "Home Page",
    version: "v1", // Add version property
    style: "CLASSIC", // Add style property
    path: "index",
    htmlId: null,
    data: {
      type: "HeroBanner",
      id: "k",
      title: "Hero Banner!",
      subTitle: "Hero Banner Sub Title is here",
      description: "Hero Banner Paragraph is here",
      version: "v1",
      style: "CLASSIC",
      services: null,
      imageDtos: null,
      bgColor: null,
    },
  },
  {
    id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
    name: "Service",
    version: "v1",
    style: "CLASSIC",
    path: "index",
    htmlId: null,
    data: {
      type: "AboutUs",
      id: "k",
      title: "Hero Banner!",
      subTitle: "Hero Banner Sub Title is here",
      description: "Hero Banner Paragraph is here",
      version: "v1",
      style: "CLASSIC",
      services: null,
      imageDtos: null,
      bgColor: null,
    },
  },
  {
    id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
    name: "Service",
    version: "v1",
    style: "CLASSIC",
    path: "index",
    htmlId: null,
    data: {
      type: "Gallery",
      id: "k",
      title: "Hero Banner!",
      subTitle: "Hero Banner Sub Title is here",
      description: "Hero Banner Paragraph is here",
      version: "v1",
      style: "CLASSIC",
      services: null,
      imageDtos: null,
      bgColor: null,
    },
  },
  {
    id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
    name: "Service",
    version: "v1",
    style: "CLASSIC",
    path: "index",
    htmlId: null,
    data: {
      type: "Product",
      id: "k",
      title: "Hero Banner!",
      subTitle: "Hero Banner Sub Title is here",
      description: "Hero Banner Paragraph is here",
      version: "v1",
      style: "CLASSIC",
      services: null,
      imageDtos: null,
      bgColor: null,
    },
  },
  {
    id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
    name: "Service",
    version: "v1",
    style: "CLASSIC",
    path: "index",
    htmlId: null,
    data: {
      type: "Service",
      id: "k",
      title: "Hero Banner!",
      subTitle: "Hero Banner Sub Title is here",
      description: "Hero Banner Paragraph is here",
      version: "v1",
      style: "CLASSIC",
      services: null,
      imageDtos: null,
      bgColor: null,
    },
  },
  {
    id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
    name: "Service",
    version: "v1",
    style: "CLASSIC",
    path: "index",
    htmlId: null,
    data: {
      type: "Blog",
      id: "k",
      title: "Hero Banner!",
      subTitle: "Hero Banner Sub Title is here",
      description: "Hero Banner Paragraph is here",
      version: "v1",
      style: "CLASSIC",
      services: null,
      imageDtos: null,
      bgColor: null,
    },
  },
  {
    id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
    name: "Service",
    version: "v1",
    style: "CLASSIC",
    path: "index",
    htmlId: null,
    data: {
      type: "ContactUs",
      id: "k",
      title: "Hero Banner!",
      subTitle: "Hero Banner Sub Title is here",
      description: "Hero Banner Paragraph is here",
      version: "v1",
      style: "CLASSIC",
      services: null,
      imageDtos: null,
      bgColor: null,
    },
  },
  {
    id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
    name: "Service",
    version: "v1",
    style: "CLASSIC",
    path: "index",
    htmlId: null,
    data: {
      type: "FAQ",
      id: "k",
      title: "Hero Banner!",
      subTitle: "Hero Banner Sub Title is here",
      description: "Hero Banner Paragraph is here",
      version: "v1",
      style: "CLASSIC",
      services: null,
      imageDtos: null,
      bgColor: null,
    },
  },
  {
    id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
    name: "Service",
    version: "v1",
    style: "CLASSIC",
    path: "index",
    htmlId: null,
    data: {
      type: "Footer",
      id: "k",
      title: "Hero Banner!",
      subTitle: "Hero Banner Sub Title is here",
      description: "Hero Banner Paragraph is here",
      version: "v1",
      style: "CLASSIC",
      services: null,
      imageDtos: null,
      bgColor: null,
    },
  },
];
