import { Section } from "../modal/Section";

export const website1: Section[] = [
  {
      id: "69e7ed7e-889d-41c0-a1d9-62bd150401e2",
      name: "Header",
      version: "v1", // Add version property
      style: "CLASSIC", // Add style property
      path: "index",
      data: {
        type: "Header",
        id: "001",
        title: "Hero Banner!",
        subTitle: "Hero Banner Sub Title is here",
        description: "Hero Banner Paragraph is here",
        version: "v1",
        style: "CLASSIC",
        services: null,
        products: null,
        portfolios: null,
        images: null,
        blogs : null,
        testimonials: null,
        faqs: null,
        contactUs:null,
      },
    },
{
  id: "69e7ed7e-889d-41c0-a1d9-62bd150401e2",
  name: "Headbanger",
  version: "v1", // Add version property
  style: "MODERN", // Add style property
  path: "index",
  data: {
    type: "HeroBanner",
    id: "002",
    title: "Software Engineer !",
    subTitle: "Loonds Spa App Alpha Vercel",
    description: "Hero Banner Paragraph is here",
    version: "v1",
    style: "MODERN",
    services: null,
    portfolios: null,
    products: null,
    images: [
      {
          id: '1',
          imageSrc: 'https://tailwindui.com/img/ecommerce-images/home-page-02-edition-01.jpg',
          imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
      },
    ],
    blogs : null,
    testimonials: null,
    faqs: null,
    contactUs:null,
  },
},
{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: "Service",
  version: "v1",
  style: "MODERN",
  path: "index",
  data: {
    type: "AboutUs",
    id: "003",
    title: "About us is here!",
    subTitle: "Hero Banner Sub Title is here",
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    version: "v1",
    style: "MODERN",
    services: null,
    products: null,
    images: null,
    blogs : null,
    testimonials: null,
    portfolios: null,
    faqs: null,
    contactUs:null,
  },
},
{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: "Gallery",
  version: "v1",
  style: "CLASSIC",
  path: "index",
  data: {
    type: "Gallery",
    id: "004",
    title: "Gallery !",
    subTitle: "Hero Banner Sub Title is here",
    description: "Hero Banner Paragraph is here",
    version: "v1",
    style: "CLASSIC",
    services: null,
    products: null,
    portfolios: null,
    faqs: null,
    images: [
      {
          id: '1',
          imageSrc: 'https://tailwindui.com/img/ecommerce-images/home-page-02-edition-01.jpg',
          imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
      },
      {
          id: '2',
          imageSrc: 'https://images.unsplash.com/photo-1684752097893-13785863f9a1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=435&q=80',
          imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
      },
      {
          id: '3',
          imageSrc: 'https://images.unsplash.com/photo-1682695797221-8164ff1fafc9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80',
          imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
      },
      {
          id: '4',
          imageSrc: 'https://images.unsplash.com/photo-1682695797221-8164ff1fafc9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80',
          imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
      },
  ],
  blogs : null,
  testimonials: null,
  contactUs:null,
  },
},
{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: "Service",
  version: "v1",
  style: "CLASSIC",
  path: "index",
  data: {
    type: "Service",
    id: "k",
    title: "Our Services",
    subTitle: "Hero Banner Sub Title is here",
    description: "Hero Banner Paragraph is here",
    version: "v1",
    style: "CLASSIC",
    blogs : null,
    faqs: null,
    contactUs:null,
    portfolios: null,
    services: [
      {
          id: 1,
          title: 'Hosting Space',
          body: 'We dejoy working with discerning clients, people for whom qualuty, service, integrity & aesthetics.',
          imageSrc: 'https://htmldemo.zcubethemes.com/riorelax/img/icon/sve-icon3.png',
          imageAlt: 'parking icon',
      },
      {
          id: 2,
          title: '27/7 Service',
          body: 'We dejoy working with discerning clients, people for whom qualuty, service, integrity & aesthetics.',
          imageSrc: 'https://htmldemo.zcubethemes.com/riorelax/img/icon/fe-icon01.png',
          imageAlt: 'parking icon',
      },
      {
          id: 3,
          title: 'Fibre Internet',
          body: 'We dejoy working with discerning clients, people for whom qualuty, service, integrity & aesthetics.',
          imageSrc: 'https://htmldemo.zcubethemes.com/riorelax/img/icon/sve-icon2.png',
          imageAlt: 'parking icon',
      },
      
    ],
    products: null,
    images: null,
    testimonials: null,
  },
},
{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: "Service",
  version: "v1",
  style: "CLASSIC",
  path: "index",
  data: {
    type: "Blog",
    id: "k",
    title: "Hero Banner!",
    subTitle: "Hero Banner Sub Title is here",
    description: "Hero Banner Paragraph is here",
    version: "v1",
    style: "CLASSIC",
    services: null,
    products: null,
    faqs: null,
    contactUs:null,
    portfolios: null,
    blogs : [
      {
        id: "1",
        title: "Blog Post 1",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        descriptionContext: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nonummy tincidunt ut lacreet dolore magna aliguam erat volutpat.",
        imageSrc: "https://images.unsplash.com/photo-1605181063694-e64a8e7a267f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=435&q=80",
        imageAlt: 'Tall slender porcelain bottle with natural clay textured body and cork stopper.',
      },
      {
        id: "2",
        title: "Blog Post 2",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        descriptionContext: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nonummy tincidunt ut lacreet dolore magna aliguam erat volutpat.",
        imageSrc: "https://plus.unsplash.com/premium_photo-1674086970773-726e445f5802?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1172&q=80",
        imageAlt: 'Tall slender porcelain bottle with natural clay textured body and cork stopper.',
      },
      {
        id: "3",
        title: "Blog Post 3",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        descriptionContext: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nonummy tincidunt ut lacreet dolore magna aliguam erat volutpat.",
        imageSrc: "https://plus.unsplash.com/premium_photo-1674086970773-726e445f5802?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1172&q=80",
        imageAlt: 'Tall slender porcelain bottle with natural clay textured body and cork stopper.',
      },
      {
        id: "4",
        title: "Blog Post 3",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        descriptionContext: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nonummy tincidunt ut lacreet dolore magna aliguam erat volutpat.",
        imageSrc: "https://plus.unsplash.com/premium_photo-1674086970773-726e445f5802?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1172&q=80",
        imageAlt: 'Tall slender porcelain bottle with natural clay textured body and cork stopper.',
      },
    ],
    images: null,
    testimonials: null,
  },
},
{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: "Service",
  version: "v1",
  style: "CLASSIC",
  path: "index",
  data: {
    type: "Testimonial",
    id: "k",
    title: "Hero Banner!",
    subTitle: "Hero Banner Sub Title is here",
    description: "Hero Banner Paragraph is here",
    version: "v1",
    style: "CLASSIC",
    services: null,
    products: null,
    images: null,
    blogs : null,
    faqs: null,
    portfolios: null,
    contactUs:null,
    testimonials: [
      {
        id: "1",
        name: "John Doe",
        designation: "Graphic Designer",
        imageSrc: "https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(2).jpg",
        imageAlt: "Graphic Designer",
        testimonial:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac magna sit amet risus tristique interdum, at vel velit in hac habitasse platea dictumst.",
    },
    {
        id: "2",
        name: "John Doe",
        designation: "John Doe",
        imageSrc: "https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(1).jpg",
        imageAlt: "John Doe",
        testimonial:
            "Praesent placerat enim ut ex tincidunt vehicula. Fusce sit amet dui tellus. Morbi sagittis, quam nec venenatis lobortis, mi risus tempus nulla, sed porttitor est nibh at nulla.",
    },
    {
        id: "3",
        name: "John Doe",
        designation: "John Doe",
        imageSrc: "https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(9).jpg",
        imageAlt: "John Doe",
        testimonial:
            "Ut posuere, ex a fringilla hendrerit, nulla metus gravida mi, in hendrerit quam odio sed est. Vestibulum nec finibus nisi. Aliquam et ipsum nulla.",
    },
    ],
  },
},
{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: "ContactUs",
  version: "v2",
  style: "CLASSIC",
  path: "index",
  data: {
    type: "ContactUs",
    id: "k",
    title: "Get in Touch",
    subTitle: "Hero Banner Sub Title is here",
    description: "Hero Banner Paragraph is here",
    version: "v2",
    style: "CLASSIC",
    services: null,
    products: null,
    images: null,
    testimonials: null,
    portfolios: null,
    faqs: null,
    blogs : null,
    contactUs: {
      address : "Village Kimughat P.O. Garkhal, Tehsil, Kasauli, Himachal Pradesh 173201",
      email: "gayatrilodgekasauli@gmail.com",
      phone: "+91-9857315551",
    },
  },
},
{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: "Faq",
  version: "v1",
  style: "CLASSIC",
  path: "index",
  data: {
    type: "FAQ",
    id: "k",
    title: "Hero Banner!",
    subTitle: "Hero Banner Sub Title is here",
    description: "Hero Banner Paragraph is here",
    version: "v1",
    style: "CLASSIC",
    services: null,
    products: null,
    images: null,
    blogs : null,
    testimonials: null,
    contactUs:null,
    portfolios: null,
    faqs: [
      {
        id:1,
        question: 'Q.What is bla bla ?',
        answer: 'Ans:The standard check-in time at Gayatri Lodge is 2:00 PM, and the check-out time is 12:00 PM (noon). However, early check-in or late check-out requests can be accommodated based on availability and may be subject to additional charges.',
      },
      {
        id:2,
        question: 'Q.What Service are provided at Loonds spa?',
        answer: 'Ans:Gayatri Lodge offers a range of amenities to make your stay comfortable. Some of the amenities include clean and well-furnished rooms, air conditioning, television, attached bathroom with hot water facility, room service, Wi-Fi access, and complimentary toiletries.',
      },
      {
        id:3,
        question: 'Q.Is there Domain parking provide loonds?',
        answer: 'Ans:Yes, Gayatri Lodge provides parking facilities for guests. You can safely park your vehicle during your stay at the lodge. However, parking availability may be limited, so its advisable to inform the lodge in advance if you require parking.',
      },
  ],
  },
},
{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: "Footer",
  version: "v1",
  style: "CLASSIC",
  path: "index",
  data: {
    type: "Footer",
    id: "k",
    title: "Hero Banner!",
    subTitle: "Hero Banner Sub Title is here",
    description: "Hero Banner Paragraph is here",
    version: "v1",
    style: "CLASSIC",
    services: null,
    portfolios: null,
    products: null,
    blogs : null,
    images: null,
    faqs: null,
    contactUs:null,
    testimonials: null,
  },
},
];
export const website2: Section[] = [
    {
      id: "69e7ed7e-889d-41c0-a1d9-62bd150401e2",
      name: "Header",
      version: "v2",
      style: "CLASSIC",
      path: "index",
      data: {
        type: "Header",
        id: "001",
        title: "DesignFusion",
        subTitle: "Hero Banner Sub Title is here",
        description: "Hero Banner Paragraph is here",
        version: "v1",
        style: "CLASSIC",
        services: null,
        products: null,
        portfolios: null,
        images: null,
        blogs : null,
        testimonials: null,
        faqs: null,
        contactUs:null,
      },
    },
{
  id: "69e7ed7e-889d-41c0-a1d9-62bd150401e2",
  name: "HeroBanner",
  version: "v1", // Add version property
  style: "CLASSIC", // Add style property
  path: "index",
  data: {
    type: "HeroBanner",
    id: "002",
    title: "Welcome to DesignFusion",
    subTitle: "Where Art Meets Architecture",
    description: "we believe that exceptional design can transform spaces into extraordinary experiences. We are a leading interior and exterior design firm dedicated to creating captivating, functional, and timeless designs for commercial buildings, hotels, shops, and more.",
    version: "v1",
    style: "CLASSIC",
    services: null,
    products: null,
    images: [
      {
        id: '1',
        imageSrc: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80',
        // imageSrc: 'https://images.unsplash.com/photo-1600585153490-76fb20a32601?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80',
        imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
    },
    ],
    blogs : null,
    testimonials: null,
    portfolios: null,
    faqs: null,
    contactUs:null,
  },
},
{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: "Service",
  version: "v1",
  style: "MODERN",
  path: "index",
  data: {
    type: "AboutUs",
    id: "003",
    title: "About us!",
    subTitle: "Hero Banner Sub Title is here",
    description: "We are passionate about design and dedicated to creating captivating spaces that inspire and delight As a leading interior and exterior design firm, we bring together artistry, innovation, and functionality to transform commercial buildings, hotels, shops, and various spaces into extraordinary works of art.\nOur talented team of designers and architects are committed to understanding your vision and turning it into reality. With years of experience in the industry, we have mastered the art of harmonizing materials like ACP, aluminum, glass, and wooden flooring to craft designs that stand the test of time.",
    version: "v1",
    style: "MODERN",
    services: null,
    products: null,
    images: [
      {
        "id": "1",
        "imageAlt": 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
        "imageSrc": "https://images.unsplash.com/photo-1600585153490-76fb20a32601?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80"
      }
    ],
    blogs : null,
    testimonials: null,
    portfolios: null,
    faqs: null,
    contactUs:null,
  },
},

{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: " ",
  version: "v1",
  style: "CLASSIC",
  path: "index",
  data: {
    type: "Product",
    id: "k",
    title: "Our Project!",
    subTitle: "Our Recent Project is here",
    description: "Hero Banner Paragraph is here",
    version: "v1",
    style: "CLASSIC",
    services: null,
    blogs : null,
    portfolios: null,
    products: [
      {
          id: 1,
          name: 'Deluxe Room',
          href: '#',
          description: 'Spacious, elegant, and luxurious accommodation for ultimate comfort.',
          imageSrc: "https://images.unsplash.com/photo-1600047509782-20d39509f26d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1001&q=80",
          imageAlt: 'Tall slender porcelain bottle with natural clay textured body and cork stopper.',
      },
      {
          id: 2,
          name: 'Master Room',
          href: '#',
          description: 'Opulent, indulgent, and exclusive retreat for discerning guests.',
          imageSrc: "https://images.unsplash.com/photo-1600585153490-76fb20a32601?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
          imageAlt: 'Olive drab green insulated bottle with flared screw lid and flat top.',
      },
      {
          id: 3,
          name: 'Super Room',
          href: '#',
          description: ' Upgraded, luxurious, and lavish accommodation for a remarkable stay.',
          imageSrc: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
          imageAlt: 'Person using a pen to cross a task off a productivity paper card.',
      },
      {
          id: 4,
          name: 'Normal Room',
          href: '#',
          description: 'Comfortable, affordable, and practical choice for a pleasant stay.',
          imageSrc: "https://images.unsplash.com/photo-1513584684374-8bab748fbf90?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1165&q=80",
          imageAlt: 'Hand holding black machined steel mechanical pencil with brass tip and top.',
      },
      {
          id: 5,
          name: 'Normal Room',
          href: '#',
          description: 'Comfortable, affordable, and practical choice for a pleasant stay.',
          imageSrc: "https://i.pinimg.com/564x/b3/ea/5c/b3ea5c2e73bcb2f375e7aaf489aa20b5.jpg",
          imageAlt: 'Hand holding black machined steel mechanical pencil with brass tip and top.',
      },
      {
          id: 6,
          name: 'Normal Room',
          href: '#',
          description: 'Comfortable, affordable, and practical choice for a pleasant stay.',
          imageSrc: "https://i.pinimg.com/736x/5b/ea/2c/5bea2c147c27cd306b03fa12bcec2c22.jpg",
          imageAlt: 'Hand holding black machined steel mechanical pencil with brass tip and top.',
      },
      // More products...
  ],
    images: null,
    faqs: null,
    testimonials: null,
    contactUs:null,
  },
},
{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: "Gallery",
  version: "v1",
  style: "MODERN",
  path: "index",
  data: {
    type: "Gallery",
    id: "004",
    title: "Sample Gallery is here!",
    subTitle: "Hero Banner Sub Title is here",
    description: "Hero Banner Paragraph is here",
    version: "v1",
    style: "MODERN",
    services: null,
    products: null,
    portfolios: null,
    faqs: null,
    images: [
      {
          id: '1',
          imageSrc: 'https://images.unsplash.com/photo-1600585153490-76fb20a32601?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80',
          imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
      },
      {
          id: '2',
          imageSrc: 'https://images.unsplash.com/photo-1600585154363-67eb9e2e2099?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80',
          imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
      },
      {
          id: '3',
          imageSrc: 'https://images.unsplash.com/photo-1600047509358-9dc75507daeb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80',
          imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
      },
      {
          id: '4',
          imageSrc: 'https://images.unsplash.com/photo-1600047509782-20d39509f26d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1001&q=80',
          imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
      },
  ],
  blogs : null,
  testimonials: null,
  contactUs:null,
  },
},
{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: "Service",
  version: "v1",
  style: "CLASSIC",
  path: "index",
  data: {
    type: "Service",
    id: "k",
    title: "Our Services",
    subTitle: "Hero Banner Sub Title is here",
    description: "Hero Banner Paragraph is here",
    version: "v1",
    style: "CLASSIC",
    blogs : null,
    faqs: null,
    contactUs:null,
    portfolios: [
      {
        id:1,
          name: 'Desk and Office',
          description: 'Work from home accessories',
          imageSrc: 'https://tailwindui.com/img/ecommerce-images/home-page-02-edition-01.jpg',
          imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
          href: '#',
      },
      {
        id:2,
          name: 'Self-Improvement',
          description: 'Journals and note-taking',
          imageSrc: 'https://tailwindui.com/img/ecommerce-images/home-page-02-edition-02.jpg',
          imageAlt: 'Wood table with porcelain mug, leather journal, brass pen, leather key ring, and a houseplant.',
          href: '#',
      },
      {
        id:3,
          name: 'Self-Improvement',
          description: 'Journals and note-taking',
          imageSrc: 'https://tailwindui.com/img/ecommerce-images/home-page-02-edition-02.jpg',
          imageAlt: 'Wood table with porcelain mug, leather journal, brass pen, leather key ring, and a houseplant.',
          href: '#',
      },
      {
        id:4,
          name: 'Self-Improvement',
          description: 'Journals and note-taking',
          imageSrc: 'https://tailwindui.com/img/ecommerce-images/home-page-02-edition-02.jpg',
          imageAlt: 'Wood table with porcelain mug, leather journal, brass pen, leather key ring, and a houseplant.',
          href: '#',
      },
      {
        id:5,
          name: 'Travel',
          description: 'Daily commute essentials',
          imageSrc: 'https://tailwindui.com/img/ecommerce-images/home-page-02-edition-03.jpg',
          imageAlt: 'Collection of four insulated travel bottles on wooden shelf.',
          href: '#',
      },
  ],
    services: [
      {
          id: 1,
          title: 'Interior Design:',
          body: 'Create captivating and functional interiors for corporate offices, hotels, and retail spaces that reflect your brand identity.',
          imageSrc: 'https://htmldemo.zcubethemes.com/riorelax/img/icon/sve-icon3.png',
          imageAlt: 'parking icon',
      },
      {
          id: 2,
          title: 'Exterior Design',
          body: ' Craft striking facades and landscape concepts for commercial buildings, hotels, and shops to leave a lasting impression.',
          imageSrc: 'https://htmldemo.zcubethemes.com/riorelax/img/icon/fe-icon01.png',
          imageAlt: 'parking icon',
      },
      {
          id: 3,
          title: 'ACP and Aluminum Design',
          body: 'Harness the versatility of ACP and aluminum to bring modern and elegant architectural visions to life.',
          imageSrc: 'https://htmldemo.zcubethemes.com/riorelax/img/icon/sve-icon2.png',
          imageAlt: 'parking icon',
      },
      {
          id: 4,
          title: 'Glass Solutions',
          body: 'Experience the elegance of glass with custom-designed facades, partitions, and skylights for seamless interior-exterior connections.',
          imageSrc: 'https://htmldemo.zcubethemes.com/riorelax/img/icon/fe-icon08.png',
          imageAlt: 'parking icon',
      },
      {
          id: 5,
          title: 'Wooden Flooring',
          body: 'Add warmth and sophistication to your spaces with hardwood, engineered wood, and laminate flooring options.',
          imageSrc: 'https://htmldemo.zcubethemes.com/riorelax/img/icon/fe-icon05.png',
          imageAlt: 'parking icon',
      },
      {
          id: 6,
          title: 'Ceiling Design',
          body: 'Elevate your interiors with innovative and artistic ceiling designs that enhance the ambiance and aesthetics of any space.',
          imageSrc: 'https://htmldemo.zcubethemes.com/riorelax/img/icon/fe-icon05.png',
          imageAlt: 'parking icon',
      },
    ],
    products: null,
    images: null,
    testimonials: null,
  },
},
{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: "Service",
  version: "v1",
  style: "CLASSIC",
  path: "index",
  data: {
    type: "Portfolio",
    id: "k",
    title: "Our Team",
    subTitle: "Hero Banner Sub Title is here",
    description: "Hero Banner Paragraph is here",
    version: "v1",
    style: "CLASSIC",
    blogs : null,
    faqs: null,
    contactUs:null,
    portfolios: [
      {
        id:1,
          name: 'Desk and Office',
          description: 'Work from home accessories',
          imageSrc: 'https://tailwindui.com/img/ecommerce-images/home-page-02-edition-01.jpg',
          imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
          href: '#',
      },
      {
        id:2,
          name: 'Self-Improvement',
          description: 'Journals and note-taking',
          imageSrc: 'https://tailwindui.com/img/ecommerce-images/home-page-02-edition-02.jpg',
          imageAlt: 'Wood table with porcelain mug, leather journal, brass pen, leather key ring, and a houseplant.',
          href: '#',
      },
      {
        id:3,
          name: 'Self-Improvement',
          description: 'Journals and note-taking',
          imageSrc: 'https://tailwindui.com/img/ecommerce-images/home-page-02-edition-02.jpg',
          imageAlt: 'Wood table with porcelain mug, leather journal, brass pen, leather key ring, and a houseplant.',
          href: '#',
      },
      {
        id:4,
          name: 'Self-Improvement',
          description: 'Journals and note-taking',
          imageSrc: 'https://tailwindui.com/img/ecommerce-images/home-page-02-edition-02.jpg',
          imageAlt: 'Wood table with porcelain mug, leather journal, brass pen, leather key ring, and a houseplant.',
          href: '#',
      },
      {
        id:5,
          name: 'Travel',
          description: 'Daily commute essentials',
          imageSrc: 'https://tailwindui.com/img/ecommerce-images/home-page-02-edition-03.jpg',
          imageAlt: 'Collection of four insulated travel bottles on wooden shelf.',
          href: '#',
      },
  ],
    services: [
      {
          id: 1,
          title: 'Interior Design:',
          body: 'Create captivating and functional interiors for corporate offices, hotels, and retail spaces that reflect your brand identity.',
          imageSrc: 'https://htmldemo.zcubethemes.com/riorelax/img/icon/sve-icon3.png',
          imageAlt: 'parking icon',
      },
      {
          id: 2,
          title: 'Exterior Design',
          body: ' Craft striking facades and landscape concepts for commercial buildings, hotels, and shops to leave a lasting impression.',
          imageSrc: 'https://htmldemo.zcubethemes.com/riorelax/img/icon/fe-icon01.png',
          imageAlt: 'parking icon',
      },
      {
          id: 3,
          title: 'ACP and Aluminum Design',
          body: 'Harness the versatility of ACP and aluminum to bring modern and elegant architectural visions to life.',
          imageSrc: 'https://htmldemo.zcubethemes.com/riorelax/img/icon/sve-icon2.png',
          imageAlt: 'parking icon',
      },
      {
          id: 4,
          title: 'Glass Solutions',
          body: 'Experience the elegance of glass with custom-designed facades, partitions, and skylights for seamless interior-exterior connections.',
          imageSrc: 'https://htmldemo.zcubethemes.com/riorelax/img/icon/fe-icon08.png',
          imageAlt: 'parking icon',
      },
      {
          id: 5,
          title: 'Wooden Flooring',
          body: 'Add warmth and sophistication to your spaces with hardwood, engineered wood, and laminate flooring options.',
          imageSrc: 'https://htmldemo.zcubethemes.com/riorelax/img/icon/fe-icon05.png',
          imageAlt: 'parking icon',
      },
      {
          id: 6,
          title: 'Ceiling Design',
          body: 'Elevate your interiors with innovative and artistic ceiling designs that enhance the ambiance and aesthetics of any space.',
          imageSrc: 'https://htmldemo.zcubethemes.com/riorelax/img/icon/fe-icon05.png',
          imageAlt: 'parking icon',
      },
    ],
    products: null,
    images: null,
    testimonials: null,
  },
},
{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: "ContactUs",
  version: "v2",
  style: "CLASSIC",
  path: "index",
  data: {
    type: "ContactUs",
    id: "k",
    title: "Get in Touch",
    subTitle: "Hero Banner Sub Title is here",
    description: "Hero Banner Paragraph is here",
    version: "v2",
    style: "CLASSIC",
    services: null,
    products: null,
    images: null,
    testimonials: null,
    faqs: null,
    portfolios: null,
    blogs : null,
    contactUs: {
      address : "Village Harnora P.O. Harnora, Tehsil, Bilaspur, Himachal Pradesh 174013",
      email: "santoshsankhyan123@gmail.com",
      phone: "+91-9805058367",
    },
  },
},
{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: "Faq",
  version: "v1",
  style: "CLASSIC",
  path: "index",
  data: {
    type: "FAQ",
    id: "k",
    title: "Hero Banner!",
    subTitle: "Hero Banner Sub Title is here",
    description: "Hero Banner Paragraph is here",
    version: "v1",
    style: "CLASSIC",
    services: null,
    products: null,
    images: null,
    blogs : null,
    testimonials: null,
    portfolios: null,
    contactUs:null,
    faqs: [
      {
        id:1,
        question: 'Q. What types of projects do you handle?',
        answer: 'Ans: We handle a diverse range of projects, including interior and exterior design for commercial buildings, hotels, retail spaces, corporate offices, and more. Our expertise covers both new construction and renovation projects.',
      },
      {
        id:2,
        question: 'Q. How involved will I be in the design process?',
        answer: 'Ans: Your input is crucial to creating a space that aligns with your vision and requirements. We believe in a collaborative approach and will work closely with you throughout the design process, from concept development to material selection, ensuring a personalized experience.',
      },
      {
        id:3,
        question: 'Q.Can you work within my budget?',
        answer: 'Ans: Absolutely! We understand the importance of budget considerations in any project. Our team is skilled at delivering innovative designs that suit your budget while maintaining the highest standards of quality and aesthetics.',
      },
      {
        id:4,
        question: 'Q. How long does the design process take?',
        answer: 'Ans: The duration of the design process varies depending on the complexity and scope of the project. We aim to deliver designs promptly, and our team will provide you with a timeline at the outset. Rest assured, we prioritize attention to detail and thorough planning.',
      },
      {
        id:5,
        question: 'Q. What materials do you work with?',
        answer: 'Ans: We specialize in working with a variety of materials, including ACP, aluminum, glass, and wooden flooring. Our expertise allows us to harness the unique properties of each material to create designs that are both visually appealing and durable.',
      },
      // Add more FAQs as needed
  ],
  },
},
{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: "Footer",
  version: "v1",
  style: "CLASSIC",
  path: "index",
  data: {
    type: "Footer",
    id: "k",
    title: "Hero Banner!",
    subTitle: "Hero Banner Sub Title is here",
    description: "Hero Banner Paragraph is here",
    version: "v1",
    style: "CLASSIC",
    services: null,
    products: null,
    blogs : null,
    portfolios: null,
    images: null,
    faqs: null,
    contactUs:null,
    testimonials: null,
  },
},
];
export const website3: Section[] = [
  {
      id: "69e7ed7e-889d-41c0-a1d9-62bd150401e2",
      name: "Header",
      version: "v1", // Add version property
      style: "MODERN", // Add style property
      path: "index",
      data: {
        type: "Header",
        id: "001",
        title: "HCreations",
        subTitle: "Hero Banner Sub Title is here",
        description: "Hero Banner Paragraph is here",
        version: "v1",
        style: "MODERN",
        services: null,
        products: null,
        portfolios: null,
        images: null,
        blogs : null,
        testimonials: null,
        faqs: null,
        contactUs:null,
      },
    },
{
  id: "69e7ed7e-889d-41c0-a1d9-62bd150401e2",
  name: "Herobanner",
  version: "v1", // Add version property
  style: "MODERN", // Add style property
  path: "index",
  data: {
    type: "HeroBanner",
    id: "002",
    title: "HCreations",
    subTitle: "Welcome to Handmade Creations - Customized Hampers That Fit Your Budget!",
    description: "Hero Banner Paragraph is here",
    version: "v2",
    style: "MODERN",
    services: null,
    products: null,
    images: null,
    blogs : null,
    testimonials: null,
    portfolios: null,
    faqs: null,
    contactUs:null,
  },
},
{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: " ",
  version: "v1",
  style: "CLASSIC",
  path: "index",
  data: {
    type: "Product",
    id: "k",
    title: "Our Product!",
    subTitle: "Hero Banner Sub Title is here",
    description: "Hero Banner Paragraph is here",
    version: "v1",
    style: "CLASSIC",
    services: null,
    blogs : null,
    portfolios: null,
    products: [
      {
          id: 1,
          name: 'Handcrafted Candles',
          href: '#',
          description: 'Spacious, elegant, and luxurious accommodation for ultimate comfort.',
          imageSrc: "https://www.moneymagpie.com/wp-content/uploads/2023/03/MoneyMagpie_Riverford-Christmas-Gift-Hamper.jpg.webp",
          imageAlt: 'Tall slender porcelain bottle with natural clay textured body and cork stopper.',
      },
      {
          id: 2,
          name: 'Artisanal Soaps and Bath Products',
          href: '#',
          description: 'Opulent, indulgent, and exclusive retreat for discerning guests.',
          imageSrc: "https://www.moneymagpie.com/wp-content/uploads/2023/03/MoneyMagpie_Riverford-Christmas-Gift-Hamper.jpg.webp",
          imageAlt: 'Olive drab green insulated bottle with flared screw lid and flat top.',
      },
      {
        id: 11,
        name: 'Handcrafted Candles',
        href: '#',
        description: 'Spacious, elegant, and luxurious accommodation for ultimate comfort.',
        imageSrc: "https://www.moneymagpie.com/wp-content/uploads/2023/03/MoneyMagpie_Riverford-Christmas-Gift-Hamper.jpg.webp",
        imageAlt: 'Tall slender porcelain bottle with natural clay textured body and cork stopper.',
    },
    {
        id: 21,
        name: 'Artisanal Soaps and Bath Products',
        href: '#',
        description: 'Opulent, indulgent, and exclusive retreat for discerning guests.',
        imageSrc: "https://www.moneymagpie.com/wp-content/uploads/2023/03/MoneyMagpie_Riverford-Christmas-Gift-Hamper.jpg.webp",
        imageAlt: 'Olive drab green insulated bottle with flared screw lid and flat top.',
    },
    {
      id: 122,
      name: 'Handmade Home Decor',
      href: '#',
      description: 'Spacious, elegant, and luxurious accommodation for ultimate comfort.',
      imageSrc: "https://www.moneymagpie.com/wp-content/uploads/2023/03/MoneyMagpie_Riverford-Christmas-Gift-Hamper.jpg.webp",
      imageAlt: 'Tall slender porcelain bottle with natural clay textured body and cork stopper.',
  },
  {
      id: 222,
      name: 'Artisanal Soaps and Bath Products',
      href: '#',
      description: 'Opulent, indulgent, and exclusive retreat for discerning guests.',
      imageSrc: "https://www.moneymagpie.com/wp-content/uploads/2023/03/MoneyMagpie_Riverford-Christmas-Gift-Hamper.jpg.webp",
      imageAlt: 'Olive drab green insulated bottle with flared screw lid and flat top.',
  },
      {
          id: 3,
          name: 'Gourmet Food and Treats',
          href: '#',
          description: ' Upgraded, luxurious, and lavish accommodation for a remarkable stay.',
          imageSrc: "https://www.moneymagpie.com/wp-content/uploads/2023/03/MoneyMagpie_Riverford-Christmas-Gift-Hamper.jpg.webp",
          imageAlt: 'Person using a pen to cross a task off a productivity paper card.',
      },
      // More products...
  ],
    images: null,
    faqs: null,
    testimonials: null,
    contactUs:null,
  },
},
{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: "Service",
  version: "v1",
  style: "MODERN",
  path: "index",
  data: {
    type: "AboutUs",
    id: "003",
    title: "At Handmade Creations",
    subTitle: "Hero Banner Sub Title is here",
    description: "We believe in the power of thoughtful gifting. Our passion for creativity and personalized experiences led us to establish our business, where we pour our heart and soul into curating stunning hampers that bring joy to both the giver and the recipient. \nWe understand that finding the perfect gift can be a challenge, especially when you're on a budget. That's why we've made it our mission to offer affordable yet exceptional hampers that don t compromise on quality or style. Our team of skilled artisans meticulously crafts each hamper, ensuring that every item is carefully selected and beautifully arranged.\nWe take pride in our commitment to using high-quality, locally sourced products in our hampers. From gourmet treats to luxury bath and body products, we strive to showcase the finest creations from talented artisans and small businesses.",
    version: "v1",
    style: "MODERN",
    services: null,
    products: null,
    images: null,
    blogs : null,
    testimonials: null,
    portfolios: null,
    faqs: null,
    contactUs:null,
  },
},
{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: "Service",
  version: "v1",
  style: "CLASSIC",
  path: "index",
  data: {
    type: "Testimonial",
    id: "k",
    title: "Hero Banner!",
    subTitle: "Hero Banner Sub Title is here",
    description: "Hero Banner Paragraph is here",
    version: "v1",
    style: "CLASSIC",
    services: null,
    products: null,
    images: null,
    blogs : null,
    faqs: null,
    contactUs:null,
    portfolios: null,
    testimonials: [
      {
        id: "1",
        name: "John Doe",
        designation: "Graphic Designer",
        imageSrc: "https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(2).jpg",
        imageAlt: "Graphic Designer",
        testimonial:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac magna sit amet risus tristique interdum, at vel velit in hac habitasse platea dictumst.",
    },
    {
        id: "2",
        name: "John Doe",
        designation: "John Doe",
        imageSrc: "https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(1).jpg",
        imageAlt: "John Doe",
        testimonial:
            "Praesent placerat enim ut ex tincidunt vehicula. Fusce sit amet dui tellus. Morbi sagittis, quam nec venenatis lobortis, mi risus tempus nulla, sed porttitor est nibh at nulla.",
    },
    {
        id: "3",
        name: "John Doe",
        designation: "John Doe",
        imageSrc: "https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(9).jpg",
        imageAlt: "John Doe",
        testimonial:
            "Ut posuere, ex a fringilla hendrerit, nulla metus gravida mi, in hendrerit quam odio sed est. Vestibulum nec finibus nisi. Aliquam et ipsum nulla.",
    },
    ],
  },
},
{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: "Gallery",
  version: "v1",
  style: "MODERN",
  path: "index",
  data: {
    type: "Gallery",
    id: "004",
    title: "Sample Gallery is here!",
    subTitle: "Hero Banner Sub Title is here",
    description: "Hero Banner Paragraph is here",
    version: "v1",
    style: "MODERN",
    services: null,
    products: null,
    portfolios: null,
    faqs: null,
    images: [
      {
          id: '1',
          imageSrc: 'https://www.moneymagpie.com/wp-content/uploads/2023/03/MoneyMagpie_Riverford-Christmas-Gift-Hamper.jpg.webp',
          imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
      },
      {
          id: '2',
          imageSrc: 'https://www.moneymagpie.com/wp-content/uploads/2023/03/MoneyMagpie_Riverford-Christmas-Gift-Hamper.jpg.webp',
          imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
      },
      {
          id: '3',
          imageSrc: 'https://images.unsplash.com/photo-1682695797221-8164ff1fafc9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80',
          imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
      },
      {
          id: '4',
          imageSrc: 'https://images.unsplash.com/photo-1682695797221-8164ff1fafc9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80',
          imageAlt: 'Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug.',
      },
  ],
  blogs : null,
  testimonials: null,
  contactUs:null,
  },
},

{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: "Service",
  version: "v1",
  style: "CLASSIC",
  path: "index",
  data: {
    type: "Blog",
    id: "k",
    title: "Hero Banner!",
    subTitle: "Hero Banner Sub Title is here",
    description: "Hero Banner Paragraph is here",
    version: "v1",
    style: "CLASSIC",
    services: null,
    products: null,
    faqs: null,
    contactUs:null,
    portfolios: null,
    blogs : [
      {
        id: "1",
        title: "Blog Post 1",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        descriptionContext: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nonummy tincidunt ut lacreet dolore magna aliguam erat volutpat.",
        imageSrc: "https://www.moneymagpie.com/wp-content/uploads/2023/03/MoneyMagpie_Riverford-Christmas-Gift-Hamper.jpg.webp",
        imageAlt: 'Tall slender porcelain bottle with natural clay textured body and cork stopper.',
      },
      {
        id: "2",
        title: "Blog Post 2",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        descriptionContext: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nonummy tincidunt ut lacreet dolore magna aliguam erat volutpat.",
        imageSrc: "https://www.moneymagpie.com/wp-content/uploads/2023/03/MoneyMagpie_Riverford-Christmas-Gift-Hamper.jpg.webp",
        imageAlt: 'Tall slender porcelain bottle with natural clay textured body and cork stopper.',
      },
      {
        id: "3",
        title: "Blog Post 3",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        descriptionContext: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nonummy tincidunt ut lacreet dolore magna aliguam erat volutpat.",
        imageSrc: "https://www.moneymagpie.com/wp-content/uploads/2023/03/MoneyMagpie_Riverford-Christmas-Gift-Hamper.jpg.webp",
        imageAlt: 'Tall slender porcelain bottle with natural clay textured body and cork stopper.',
      },
      {
        id: "4",
        title: "Blog Post 3",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        descriptionContext: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nonummy tincidunt ut lacreet dolore magna aliguam erat volutpat.",
        imageSrc: "https://www.moneymagpie.com/wp-content/uploads/2023/03/MoneyMagpie_Riverford-Christmas-Gift-Hamper.jpg.webp",
        imageAlt: 'Tall slender porcelain bottle with natural clay textured body and cork stopper.',
      },
    ],
    images: null,
    testimonials: null,
  },
},

{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: "ContactUs",
  version: "v2",
  style: "CLASSIC",
  path: "index",
  data: {
    type: "ContactUs",
    id: "k",
    title: "Get in Touch",
    subTitle: "Hero Banner Sub Title is here",
    description: "Hero Banner Paragraph is here",
    version: "v2",
    style: "CLASSIC",
    services: null,
    products: null,
    images: null,
    testimonials: null,
    faqs: null,
    portfolios: null,
    blogs : null,
    contactUs: {
      address : "Village Kimughat P.O. Garkhal, Tehsil, Kasauli, Himachal Pradesh 173201",
      email: "gayatrilodgekasauli@gmail.com",
      phone: "+91-9857315551",
    },
  },
},
{
  id: "143d8df3-49c7-4370-9e0e-0c5ef7a46f6b",
  name: "Footer",
  version: "v1",
  style: "CLASSIC",
  path: "index",
  data: {
    type: "Footer",
    id: "k",
    title: "Hero Banner!",
    subTitle: "Hero Banner Sub Title is here",
    description: "Hero Banner Paragraph is here",
    version: "v1",
    style: "CLASSIC",
    services: null,
    products: null,
    blogs : null,
    portfolios: null,
    images: null,
    faqs: null,
    contactUs:null,
    testimonials: null,
  },
},
];
export const basic: Section[] = [
  {
    id: "69e7ed7e-889d-41c0-a1d9-62bd150401e2",
    name: "Header",
    version: "v1", // Add version property
    style: "CLASSIC", // Add style property
    path: "index",
    data: {
      type: "ComingSoon",
      id: "001",
      title: "Comming Soon ",
      subTitle: "Hero Banner Sub Title is here",
      description: "Hero Banner Paragraph is here",
      version: "v1",
      style: "CLASSIC",
      services: null,
      products: null,
      portfolios: null,
      images: null,
      blogs : null,
      testimonials: null,
      faqs: null,
      contactUs:null,
    },
  },
];
